#!/usr/bin/env python3
"""R3(e) — ★ WHAT THE SHIPPED STOPPING RULE WOULD HAVE CHOSEN ON EVERY MARGIN
CURVE THIS LINE OF WORK HAS MEASURED, against what each run actually returned.

★ THE RULE IS REPLAYED, NOT RE-DESCRIBED. The loop below is the same three
decisions `plsm_optimize` makes:

    improved := margin > best * (1 + tol)          tol = margin_plateau_tol
    stale    += 1 when not improved, reset to 0 when improved
    stop when stale >= margin_plateau_probes, and RETURN THE PEAK ITERATE

with the shipped defaults margin_plateau_probes = 3 and margin_plateau_tol =
0.005. A probe that is not load-path connected, or whose certification solve did
not converge, is discarded before any of that; every certificate in these curves
was ACCEPTED, so nothing is discarded here.

★ THE CADENCE IS THE CURVE'S OWN AND IT IS NAMED PER ROW. The shipped cadence is
10 iterations. PR 327's curves were sampled every 10 and are replayed exactly.
Stage A's were sampled every 20, so three consecutive non-improving probes there
span 60 iterations rather than 30 — the rule stops LATER on that data than it
would on a cadence-10 run, and where that changes the answer the row says so.

Sources, none of them retyped from a handoff:
  Stage A   evidence/2026-08-12-plsm-penalty-production/margin_curves.txt
            (branch claude/plsm-minimize-surface-smoothness-902654)
  PR 327    docs/handoffs/2026-08-12-exact-volume-fraction-ersatz.md section 3(d),
            regenerated by that task's certify.sh from its own snapshots.
"""

TOL = 0.005
WINDOW = 3

CURVES = [
    # (name, rung label, cadence, [(iteration, margin)...], what the run RETURNED)
    ("L0_none        Stage A control", "0.5283 light", 20,
     [(40, 1682.0), (60, 2025.5), (80, 2609.1), (100, 2344.1), (120, 2183.2)],
     ("it120", 2183.2)),
    ("L1_perim1      Stage A C=1", "0.5283 light", 20,
     [(40, 1988.2), (60, 2384.9), (80, 1920.3), (100, 2220.7), (120, 1930.9)],
     ("it120", 1930.9)),
    ("E2_c1_eta2     Stage A C=1 eta=2", "0.7973 shipped", 20,
     [(40, 3251.4), (60, 3246.8), (80, 3253.2), (100, 3252.2), (120, 3252.3)],
     ("it120", 3252.3)),
    ("E1_c1_eta1     Stage A C=1 eta=1", "0.7973 shipped", 20,
     [(40, 3251.8), (60, 3251.9), (80, 3249.4), (100, 3253.9), (120, 3251.0)],
     ("it120", 3251.0)),
    ("H1_heaviside   PR 327 control", "0.68 probe path", 10,
     [(10, 1915), (20, 1965), (30, 2105), (40, 2418), (50, 2734), (60, 2923),
      (70, 3233), (80, 3276), (90, 3273), (100, 3198), (110, 3161), (120, 2640)],
     ("it120", 2640.4)),
    ("F1_frac4       PR 327 arm 1", "0.68 probe path", 10,
     [(10, 2262), (20, 2372), (30, 2606), (40, 3068), (50, 3379)],
     ("it57 compliance-plateau", 3379.4)),
    ("A2_all         PR 327 arm 2", "0.68 probe path", 10,
     [(10, 2295), (20, 2560), (30, 2968), (40, 3076), (50, 3392), (60, 3391)],
     ("it61 compliance-plateau", 3391.1)),
]


def replay(points):
    """Returns (stop_iteration or None, peak_iteration, peak_margin)."""
    best = None
    best_it = None
    stale = 0
    for it, m in points:
        if best is None or m > best * (1.0 + TOL):
            best, best_it, stale = m, it, 0
        else:
            stale += 1
            if stale >= WINDOW:
                return it, best_it, best
    return None, best_it, best


hdr = ("arm", "rung", "cad", "would stop", "would return", "actually returned",
       "delta")
print(f"{hdr[0]:<34}{hdr[1]:<16}{hdr[2]:>4}  {hdr[3]:<12}{hdr[4]:<16}"
      f"{hdr[5]:<26}{hdr[6]:>9}")
print("-" * 122)
for name, rung, cad, pts, (ret_label, ret_val) in CURVES:
    stop_it, peak_it, peak = replay(pts)
    stop_s = f"it{stop_it}" if stop_it is not None else f"ran out (it{pts[-1][0]})"
    delta = (peak - ret_val) / ret_val * 100.0
    print(f"{name:<34}{rung:<16}{cad:>4}  {stop_s:<12}"
          f"{('it%d  %.1f' % (peak_it, peak)):<16}"
          f"{('%s  %.1f' % (ret_label, ret_val)):<26}{delta:>+8.1f}%")
print()
print("★ The 'delta' column is what STOPPING AT THE PEAK recovers over what the")
print("  run actually returned. Positive means the shipped rule would have")
print("  returned a BETTER-CERTIFIED design than the run did.")
