// swift-tools-version:5.9
// TopOptKit — the Swift/C++ bridge over the topopt core library (ROADMAP M7.1).
//
// Layout: `TopOptBridge` is the C++ facade target (interop-clean header +
// bridge.cpp over the core). `TopOptKit` is the Swift wrapper the app and tests
// use. `TopOptKitTests` exercises the wrapper headlessly on macOS — the M7
// verification standard is `xcodebuild test` on this package (raw output in the
// handoff), since /app/ is not covered by Linux CI (ROADMAP M7 rules).
//
// The core is built into this package by CMake as a multi-platform static-library
// xcframework (`vendor/TopOptCore.xcframework`) by `../scripts/build_core.sh`.
//
// OpenCASCADE on iOS (M7.1b): STEP import needs OCCT. On macOS it is the Homebrew
// dylibs, linked via the -L flags below. On iOS it is delivered as cross-built
// dynamic-framework xcframeworks under `vendor/occt-ios/` (from
// `../scripts/build_occt_ios.sh`; LGPL 2.1 dynamic linking, ARCHITECTURE §4/§10),
// which the app links + embeds through the `TopOptOCCT` product.
//
// WHY a generated list instead of globbing vendor/occt-ios at manifest time:
// SwiftPM caches the *compiled manifest* keyed on THIS FILE's contents. Dropping
// xcframeworks into vendor/ does NOT invalidate that cache, and a clean *build*
// (or even Reset Package Caches being forgotten) leaves Xcode resolving a stale,
// OCCT-free manifest — which is exactly why the first M7.1b wiring linked nothing
// into the app. So the framework list lives in THIS FILE, written by
// build_occt_ios.sh: editing it changes the manifest contents, which reliably
// forces SwiftPM/Xcode to re-evaluate and pick up the frameworks. The committed
// value is EMPTY (OCCT-free) so a fresh checkout and the macOS test path build
// with no iOS binaries declared; treat a populated list like vendor/ (generated,
// not committed).
import Foundation
import PackageDescription

let packageDir = URL(fileURLWithPath: #filePath).deletingLastPathComponent().path

// ==== BEGIN generated by scripts/build_occt_ios.sh — do not edit by hand ====
let iosOCCTFrameworks: [String] = []
let iosLib3mfFrameworks: [String] = []
// ==== END generated ====

let iosBinaryNames = iosOCCTFrameworks + iosLib3mfFrameworks
let hasIOSOCCT = !iosOCCTFrameworks.isEmpty

// One binaryTarget per produced xcframework (paths exist because the generating
// script produced them; empty list -> none declared -> no missing-path errors).
let iosBinaryTargets: [Target] =
    iosOCCTFrameworks.map { .binaryTarget(name: $0, path: "vendor/occt-ios/\($0).xcframework") } +
    iosLib3mfFrameworks.map { .binaryTarget(name: $0, path: "vendor/lib3mf-ios/\($0).xcframework") }

// STEP import/tagging is compiled where OpenCASCADE is linked: always macOS, and
// iOS too once the iOS OCCT frameworks are present. Elsewhere the bridge returns
// a clear "not available on this platform" error.
let occtPlatforms: [Platform] = hasIOSOCCT ? [.macOS, .iOS] : [.macOS]

var packageTargets: [Target] = [
    // The CMake-built core, per-platform, selected automatically by Xcode.
    .binaryTarget(name: "TopOptCore", path: "vendor/TopOptCore.xcframework"),
    .target(
        name: "TopOptBridge",
        // The OCCT frameworks are linked into the app through the TopOptOCCT
        // product (below); the bridge itself references OCCT only through the
        // core, so it needs no binary dependency — just the compile define.
        dependencies: ["TopOptCore"],
        cxxSettings: [
            .headerSearchPath("../../vendor/include"),
            .define("TOPOPT_BRIDGE_HAS_OCCT", .when(platforms: occtPlatforms)),
            // -stdlib=libc++ so the C++ standard-library include path reaches
            // the module build under Xcode's explicit-modules scanner, where
            // the module is compiled as C++ (requires cplusplus) but the
            // libc++ search path can otherwise be absent -> "'cstdint' file
            // not found".
            .unsafeFlags(["-std=c++17", "-stdlib=libc++"]),
        ]
    ),
    .target(
        name: "TopOptKit",
        dependencies: ["TopOptBridge"],
        swiftSettings: [.interoperabilityMode(.Cxx)],
        linkerSettings: [
            // OpenCASCADE on macOS is the Homebrew dylibs (the macOS core slice
            // contains the STEP importer there). Absolute -L path derived from the
            // manifest location so it resolves when an app links TopOptKit. On iOS,
            // OCCT comes from the embedded xcframeworks via the TopOptOCCT product.
            .unsafeFlags([
                "-L\(packageDir)/vendor/occt-lib",
                "-lTKDESTEP", "-lTKXSBase", "-lTKDE", "-lTKMesh",
                "-lTKTopAlgo", "-lTKGeomAlgo", "-lTKPrim", "-lTKBRep",
                "-lTKGeomBase", "-lTKG3d", "-lTKG2d", "-lTKMath", "-lTKernel",
            ], .when(platforms: [.macOS])),
        ]
    ),
    .testTarget(
        name: "TopOptKitTests",
        dependencies: ["TopOptKit"],
        swiftSettings: [.interoperabilityMode(.Cxx)]
    ),
    // M7.2 design system: SwiftUI-only, no C++ interop (so it needs none of
    // the bridge's Cxx build settings and stays cross-platform).
    .target(
        name: "TopOptDesign"
    ),
    .testTarget(
        name: "TopOptDesignTests",
        dependencies: ["TopOptDesign"]
    ),
    // M7.3 flow: depends on TopOptKit, so it must also enable C++ interop
    // (a Swift module built with Cxx interop forces its consumers to enable it).
    .target(
        name: "TopOptFlows",
        dependencies: ["TopOptKit", "TopOptDesign"],
        swiftSettings: [.interoperabilityMode(.Cxx)]
    ),
    .testTarget(
        name: "TopOptFlowsTests",
        dependencies: ["TopOptFlows"],
        swiftSettings: [.interoperabilityMode(.Cxx)]
    ),
    // Carrier for the iOS OCCT/lib3mf frameworks. The app's xcodeproj links the
    // `TopOptOCCT` product; the shim keeps that product valid on an OCCT-free
    // checkout, and the binary xcframeworks (when present) are listed in the
    // product so Xcode links + embeds them into the app. See TopOptOCCTShim.swift.
    .target(name: "TopOptOCCTShim"),
]
// The detected iOS OCCT/lib3mf binary targets (empty until build_occt_ios.sh).
packageTargets += iosBinaryTargets

let package = Package(
    name: "TopOptKit",
    platforms: [.macOS(.v13), .iOS(.v16)],
    products: [
        .library(name: "TopOptKit", targets: ["TopOptKit"]),
        // The M7.2 SwiftUI design system (tokens + reusable glass views).
        .library(name: "TopOptDesign", targets: ["TopOptDesign"]),
        // The M7.3 home + import flow (AppModel + Home/Import/Workspace screens).
        .library(name: "TopOptFlows", targets: ["TopOptFlows"]),
        // The iOS OCCT/lib3mf frameworks, vended to the app. Listing the binary
        // targets directly in the product is the SwiftPM binary-distribution
        // pattern that makes Xcode link + embed them into an app that depends on
        // the product. Always includes the shim so the product exists OCCT-free.
        .library(name: "TopOptOCCT", targets: ["TopOptOCCTShim"] + iosBinaryNames),
    ],
    targets: packageTargets,
    cxxLanguageStandard: .cxx17
)
