// RemoteRunnerE2ETests — the FIRST real exercise of RemoteRunner (handoff 097).
//
// RemoteRunner had never been compiled or run before this task. These tests drive
// the REAL RunModel + RemoteRunner against a REAL tools/topopt-worker/ server on
// 127.0.0.1 (reachable from the iOS simulator), proving the LAN-offload data path
// the run/results screens render over: submit -> live progress -> streamed variant
// -> final variants, plus every negative control.
//
// They are GATED on the env var TOPOPT_E2E=1 (and a worker on TOPOPT_WORKER_PORT),
// so a normal `xcodebuild test` — which has no worker running — SKIPS them and
// stays green. The handoff-097 harness sets the env + launches the worker (with a
// protocol-faithful stub topopt-cli) and captures this test's stdout as the
// app-side event log. TOPOPT_E2E_CASE selects which scenario to assert.

import XCTest
import TopOptKit
@testable import TopOptFlows

@MainActor
final class RemoteRunnerE2ETests: XCTestCase {

    // Config comes from a host file the harness writes (env vars don't reliably
    // propagate into a simulator test process, but a simulator process CAN read a
    // host path). Env overrides it for a macOS-destination run.
    private static let cfg: [String: String] = {
        let env = ProcessInfo.processInfo.environment
        var out: [String: String] = [:]
        if let data = FileManager.default.contents(atPath: "/tmp/topopt-e2e.json"),
           let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            for (k, v) in obj { out[k] = "\(v)" }
        }
        for k in ["TOPOPT_E2E", "TOPOPT_E2E_CASE", "TOPOPT_WORKER_PORT"] {
            if let v = env[k] { out[k] = v }
        }
        return out
    }()
    private var port: Int { Int(Self.cfg["TOPOPT_WORKER_PORT"] ?? "8778") ?? 8778 }
    private var e2eCase: String { Self.cfg["TOPOPT_E2E_CASE"] ?? "happy" }
    private var enabled: Bool { Self.cfg["TOPOPT_E2E"] == "1" }
    /// The fingerprint the app was built against (generated by build_core.sh).
    private var appFingerprint: String { CoreFingerprint.value }

    // A STEP request so the loadcase path is taken; the model file is a throwaway
    // (the worker's stub CLI does not import it — it drives the transport only).
    private func makeRequest() throws -> RunRequest {
        let dir = NSTemporaryDirectory()
        let path = (dir as NSString).appendingPathComponent("e2e-model.step")
        try Data("ISO-10303-21;\nENDSEC;\n".utf8).write(to: URL(fileURLWithPath: path))
        return RunRequest(modelPath: path, material: "PLA", materialsPath: "",
                          rulesPath: "", resolution: 32, projectName: "E2E",
                          anchorFaceIDs: [1, 2], loadGroups: [], minimizePlastic: true)
    }

    private func config(fingerprint: String? = nil, port: Int? = nil) -> RemoteRunnerConfig {
        RemoteRunnerConfig(host: "127.0.0.1", port: port ?? self.port,
                           expectedFingerprint: fingerprint ?? appFingerprint,
                           timeout: 30)
    }

    func testEndToEnd() throws {
        try XCTSkipUnless(enabled, "set TOPOPT_E2E=1 (and run a worker) to exercise")
        print("== E2E case=\(e2eCase) port=\(port) appFingerprint=\(appFingerprint) ==")
        switch e2eCase {
        case "happy":     try runHappyPathThroughRunModel()
        case "mismatch":  try runFingerprintMismatch()
        case "offline":   try runWorkerOffline()
        case "bad_mesh":  try runBadMeshSurfacesError()
        case "reject_all": try runAllRejected()
        case "cancel":    try runCancelMidRun()
        default: XCTFail("unknown TOPOPT_E2E_CASE \(e2eCase)")
        }
    }

    // MARK: happy path — the full RunModel/results data path

    private func runHappyPathThroughRunModel() throws {
        let model = RunModel(runner: RunModel.remoteRunner(config()))
        let progressSeen = expectation(description: "progress tick")
        progressSeen.assertForOverFulfill = false
        let firstVariant = expectation(description: "streamed variant appears")
        firstVariant.assertForOverFulfill = false
        let resolved = expectation(description: "run resolves")

        let obs = Observer(model: model) { phase, progress, outcome in
            if progress != nil {
                print("  app progress: \(progress!.stageLabel) — \(progress!.percent)%")
                progressSeen.fulfill()
            }
            if let n = outcome?.variants.count, n >= 1 {
                print("  app streamed: outcome now has \(n) variant(s), remote=\(outcome!.computedRemotely)")
                firstVariant.fulfill()
            }
            if phase != .running && phase != .idle {
                print("  app resolved: phase=\(phase)")
                resolved.fulfill()
            }
        }
        model.start(try makeRequest())
        wait(for: [progressSeen, firstVariant, resolved], timeout: 30)
        obs.stop()

        XCTAssertEqual(model.phase, .succeeded, "a happy remote run should succeed")
        let outcome = try XCTUnwrap(model.outcome)
        XCTAssertTrue(outcome.computedRemotely, "outcome must be flagged remote (fix 3)")
        XCTAssertEqual(outcome.variants.count, 2, "two accepted variants")
        for v in outcome.variants {
            XCTAssertFalse(v.meshVertices.isEmpty, "every variant carries its fetched mesh")
            XCTAssertGreaterThan(v.meshTriangleCount, 0)
            XCTAssertEqual(v.massGrams, 0, "mass is unavailable over the wire (rendered n/a)")
            XCTAssertTrue(v.vonMisesField.isEmpty, "no stress field over the wire")
        }
        print("  RESULT: succeeded, \(outcome.variants.count) variants, "
            + "worst margins \(outcome.variants.map { String(format: "%.2f", $0.worstCaseMargin) })")
    }

    // MARK: negative controls (driven directly through the Runner)

    private func drive(_ config: RemoteRunnerConfig, keepGoing: @escaping () -> Bool = { true })
        throws -> (outcome: OptimizeOutcome?, error: Error?, streamed: Int, progress: Int) {
        let runner = RunModel.remoteRunner(config)
        let lock = NSLock()
        var streamed = 0, progress = 0
        var result: OptimizeOutcome?; var thrown: Error?
        let done = expectation(description: "runner returns")
        DispatchQueue.global().async {
            do {
                result = try runner(try self.makeRequest(),
                    { _, _, _ in lock.lock(); progress += 1; lock.unlock(); return keepGoing() },
                    { _ in lock.lock(); streamed += 1; lock.unlock() })
            } catch { thrown = error }
            done.fulfill()
        }
        wait(for: [done], timeout: 30)
        return (result, thrown, streamed, progress)
    }

    private func runFingerprintMismatch() throws {
        let r = try drive(config(fingerprint: "0000deadbeef"))
        let err = try XCTUnwrap(r.error, "a fingerprint mismatch must be refused")
        print("  refused before submit: \(err)")
        XCTAssertTrue("\(err)".contains("mismatch"), "message names the skew")
        XCTAssertEqual(r.progress, 0, "no run started")
        XCTAssertEqual(r.streamed, 0, "no variant fetched")
    }

    private func runWorkerOffline() throws {
        // A dead port: must fail FAST with a clear message, not hang.
        let r = try drive(config(port: 1))
        let err = try XCTUnwrap(r.error, "an offline worker must fail, not hang")
        print("  offline failure: \(err)")
        XCTAssertNil(r.outcome)
    }

    private func runBadMeshSurfacesError() throws {
        // Worker started in TOPOPT_STUB_MODE=bad_mesh: announces a variant but its
        // mesh file 404s. RemoteRunner must fail loudly, never show an empty part.
        let r = try drive(config())
        let err = try XCTUnwrap(r.error, "a failed mesh fetch must surface an error")
        print("  mesh-fetch failure surfaced: \(err)")
        XCTAssertTrue("\(err)".lowercased().contains("mesh"), "message names the mesh")
        XCTAssertFalse((r.outcome?.variants.contains { $0.meshVertices.isEmpty }) ?? false,
                       "never returns an empty-mesh variant")
    }

    private func runAllRejected() throws {
        // Worker in TOPOPT_STUB_MODE=reject_all: report has a ladder, nothing accepted.
        let r = try drive(config())
        XCTAssertNil(r.error, "an all-rejected run is a normal outcome, not an error")
        let o = try XCTUnwrap(r.outcome)
        print("  all-rejected: acceptedCount=\(o.acceptedCount), terminal margin=\(o.variants.last?.worstCaseMargin ?? -1)")
        XCTAssertEqual(o.acceptedCount, 0)
        XCTAssertGreaterThan(o.variants.count, 0, "carries the ladder for the failure sheet")
    }

    private func runCancelMidRun() throws {
        // Worker in TOPOPT_STUB_MODE=slow: cancel after the first progress tick.
        let cancelAfterFirst = { () -> Bool in false }   // returning false == user cancel
        let r = try drive(config(), keepGoing: cancelAfterFirst)
        print("  cancel: outcome.cancelled=\(r.outcome?.cancelled ?? false), error=\(String(describing: r.error))")
        let o = try XCTUnwrap(r.outcome, "cancel returns a cancelled outcome, not a throw")
        XCTAssertTrue(o.cancelled, "a cancelled remote run returns a cancelled outcome")
    }
}

/// Observes a RunModel's @Published state on the main actor (Combine sink).
@MainActor
private final class Observer {
    private var cancellables: [Any] = []
    init(model: RunModel, _ onChange: @escaping (RunPhase, RunProgress?, OptimizeOutcome?) -> Void) {
        // Poll via a lightweight timer: RunModel's fields are @Published but this
        // avoids importing Combine plumbing; a 20ms cadence is ample for the test.
        let t = Timer.scheduledTimer(withTimeInterval: 0.02, repeats: true) { _ in
            Task { @MainActor in onChange(model.phase, model.progress, model.outcome) }
        }
        cancellables.append(t)
    }
    func stop() { for c in cancellables { (c as? Timer)?.invalidate() } }
}
