// RemoteRunnerE2ETests — the FIRST real exercise of RemoteRunner (handoff 097).
//
// RemoteRunner had never been compiled or run before this task. These tests drive
// the REAL RunModel + RemoteRunner against a REAL tools/topopt-worker/ server on
// 127.0.0.1 (reachable from the iOS simulator), proving the LAN-offload data path
// the run/results screens render over: submit -> live progress -> streamed variant
// -> final variants, plus every negative control.
//
// They are GATED on the env var TOPOPT_E2E=1 (and a worker on TOPOPT_WORKER_PORT),
// so a normal `xcodebuild test` — which has no worker running — SKIPS them and
// stays green. The handoff-097 harness sets the env + launches the worker (with a
// protocol-faithful stub topopt-cli) and captures this test's stdout as the
// app-side event log. TOPOPT_E2E_CASE selects which scenario to assert.

import XCTest
import TopOptKit
@testable import TopOptFlows

@MainActor
final class RemoteRunnerE2ETests: XCTestCase {

    // Config comes from a host file the harness writes (env vars don't reliably
    // propagate into a simulator test process, but a simulator process CAN read a
    // host path). Env overrides it for a macOS-destination run.
    private static let cfg: [String: String] = {
        let env = ProcessInfo.processInfo.environment
        var out: [String: String] = [:]
        if let data = FileManager.default.contents(atPath: "/tmp/topopt-e2e.json"),
           let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            for (k, v) in obj { out[k] = "\(v)" }
        }
        for k in ["TOPOPT_E2E", "TOPOPT_E2E_CASE", "TOPOPT_WORKER_PORT",
                  "TOPOPT_INACTIVITY_GRACE", "TOPOPT_PROXY_LOG"] {
            if let v = env[k] { out[k] = v }
        }
        return out
    }()
    private var port: Int { Int(Self.cfg["TOPOPT_WORKER_PORT"] ?? "8778") ?? 8778 }
    private var e2eCase: String { Self.cfg["TOPOPT_E2E_CASE"] ?? "happy" }
    private var enabled: Bool { Self.cfg["TOPOPT_E2E"] == "1" }
    /// Inactivity grace the harness dials down so the progress-based liveness paths
    /// (slow_sparse, worker-unreachable) are provable in seconds, not the 180s
    /// production default.
    private var inactivityGrace: TimeInterval {
        TimeInterval(Self.cfg["TOPOPT_INACTIVITY_GRACE"] ?? "") ?? 3
    }
    /// The proxy's request log (worker_dies control): the harness points this at a
    /// file the recording proxy appends every client request to, so the test can
    /// ASSERT no DELETE was ever sent when the worker died.
    private var proxyLogPath: String? { Self.cfg["TOPOPT_PROXY_LOG"] }
    /// The fingerprint the app was built against (generated by build_core.sh).
    private var appFingerprint: String { CoreFingerprint.value }

    // A STEP request so the loadcase path is taken; the model file is a throwaway
    // (the worker's stub CLI does not import it — it drives the transport only).
    private func makeRequest() throws -> RunRequest {
        let dir = NSTemporaryDirectory()
        let path = (dir as NSString).appendingPathComponent("e2e-model.step")
        try Data("ISO-10303-21;\nENDSEC;\n".utf8).write(to: URL(fileURLWithPath: path))
        return RunRequest(modelPath: path, material: "PLA", materialsPath: "",
                          rulesPath: "", resolution: 32, projectName: "E2E",
                          anchorFaceIDs: [1, 2], loadGroups: [], minimizePlastic: true)
    }

    private func config(fingerprint: String? = nil, port: Int? = nil) -> RemoteRunnerConfig {
        // Liveness config (handoff 101): a SHORT inactivity grace + short control
        // timeout so the progress-based paths resolve in seconds under test; the
        // request/resource timeouts of production are irrelevant here (no wall clock).
        RemoteRunnerConfig(host: "127.0.0.1", port: port ?? self.port,
                           expectedFingerprint: fingerprint ?? appFingerprint,
                           inactivityGrace: inactivityGrace,
                           requestTimeout: 30, controlTimeout: 5)
    }

    func testEndToEnd() throws {
        try XCTSkipUnless(enabled, "set TOPOPT_E2E=1 (and run a worker) to exercise")
        print("== E2E case=\(e2eCase) port=\(port) grace=\(inactivityGrace)s appFingerprint=\(appFingerprint) ==")
        switch e2eCase {
        case "happy":       try runHappyPathThroughRunModel()
        case "mismatch":    try runFingerprintMismatch()
        case "offline":     try runWorkerOffline()
        case "bad_mesh":    try runBadMeshSurfacesError()
        case "reject_all":  try runAllRejected()
        case "cancel":      try runCancelMidRun()
        case "slow_sparse": try runSlowSparseCompletes()
        case "stream_drop": try runStreamDropReconnects()
        case "worker_dies": try runWorkerDiesUnreachable()
        default: XCTFail("unknown TOPOPT_E2E_CASE \(e2eCase)")
        }
    }

    // MARK: happy path — the full RunModel/results data path

    private func runHappyPathThroughRunModel() throws {
        let model = RunModel(runner: RunModel.remoteRunner(config()))
        let progressSeen = expectation(description: "progress tick")
        progressSeen.assertForOverFulfill = false
        let firstVariant = expectation(description: "streamed variant appears")
        firstVariant.assertForOverFulfill = false
        let resolved = expectation(description: "run resolves")

        let obs = Observer(model: model) { phase, progress, outcome in
            if progress != nil {
                print("  app progress: \(progress!.stageLabel) — \(progress!.percent)%")
                progressSeen.fulfill()
            }
            if let n = outcome?.variants.count, n >= 1 {
                print("  app streamed: outcome now has \(n) variant(s), remote=\(outcome!.computedRemotely)")
                firstVariant.fulfill()
            }
            if phase != .running && phase != .idle {
                print("  app resolved: phase=\(phase)")
                resolved.fulfill()
            }
        }
        model.start(try makeRequest())
        wait(for: [progressSeen, firstVariant, resolved], timeout: 30)
        obs.stop()

        XCTAssertEqual(model.phase, .succeeded, "a happy remote run should succeed")
        let outcome = try XCTUnwrap(model.outcome)
        XCTAssertTrue(outcome.computedRemotely, "outcome must be flagged remote (fix 3)")
        XCTAssertEqual(outcome.variants.count, 2, "two accepted variants")
        for v in outcome.variants {
            XCTAssertFalse(v.meshVertices.isEmpty, "every variant carries its fetched mesh")
            XCTAssertGreaterThan(v.meshTriangleCount, 0)
            XCTAssertEqual(v.massGrams, 0, "mass is unavailable over the wire (rendered n/a)")
            XCTAssertTrue(v.vonMisesField.isEmpty, "no stress field over the wire")
        }
        print("  RESULT: succeeded, \(outcome.variants.count) variants, "
            + "worst margins \(outcome.variants.map { String(format: "%.2f", $0.worstCaseMargin) })")
    }

    // MARK: negative controls (driven directly through the Runner)

    private func drive(_ config: RemoteRunnerConfig, timeout: TimeInterval = 30,
                       keepGoing: @escaping () -> Bool = { true })
        throws -> (outcome: OptimizeOutcome?, error: Error?, streamed: Int, progress: Int) {
        let runner = RunModel.remoteRunner(config)
        let lock = NSLock()
        var streamed = 0, progress = 0
        var result: OptimizeOutcome?; var thrown: Error?
        let done = expectation(description: "runner returns")
        DispatchQueue.global().async {
            do {
                result = try runner(try self.makeRequest(),
                    { _, _, _ in lock.lock(); progress += 1; lock.unlock(); return keepGoing() },
                    { _ in lock.lock(); streamed += 1; lock.unlock() })
            } catch { thrown = error }
            done.fulfill()
        }
        wait(for: [done], timeout: timeout)
        return (result, thrown, streamed, progress)
    }

    private func runFingerprintMismatch() throws {
        let r = try drive(config(fingerprint: "0000deadbeef"))
        let err = try XCTUnwrap(r.error, "a fingerprint mismatch must be refused")
        print("  refused before submit: \(err)")
        XCTAssertTrue("\(err)".contains("mismatch"), "message names the skew")
        XCTAssertEqual(r.progress, 0, "no run started")
        XCTAssertEqual(r.streamed, 0, "no variant fetched")
    }

    private func runWorkerOffline() throws {
        // A dead port: must fail FAST with a clear message, not hang.
        let r = try drive(config(port: 1))
        let err = try XCTUnwrap(r.error, "an offline worker must fail, not hang")
        print("  offline failure: \(err)")
        XCTAssertNil(r.outcome)
    }

    private func runBadMeshSurfacesError() throws {
        // Worker started in TOPOPT_STUB_MODE=bad_mesh: announces a variant but its
        // mesh file 404s. RemoteRunner must fail loudly, never show an empty part.
        let r = try drive(config())
        let err = try XCTUnwrap(r.error, "a failed mesh fetch must surface an error")
        print("  mesh-fetch failure surfaced: \(err)")
        XCTAssertTrue("\(err)".lowercased().contains("mesh"), "message names the mesh")
        XCTAssertFalse((r.outcome?.variants.contains { $0.meshVertices.isEmpty }) ?? false,
                       "never returns an empty-mesh variant")
    }

    private func runAllRejected() throws {
        // Worker in TOPOPT_STUB_MODE=reject_all: report has a ladder, nothing accepted.
        let r = try drive(config())
        XCTAssertNil(r.error, "an all-rejected run is a normal outcome, not an error")
        let o = try XCTUnwrap(r.outcome)
        print("  all-rejected: acceptedCount=\(o.acceptedCount), terminal margin=\(o.variants.last?.worstCaseMargin ?? -1)")
        XCTAssertEqual(o.acceptedCount, 0)
        XCTAssertGreaterThan(o.variants.count, 0, "carries the ladder for the failure sheet")
    }

    private func runCancelMidRun() throws {
        // Worker in TOPOPT_STUB_MODE=slow: cancel after the first progress tick.
        let cancelAfterFirst = { () -> Bool in false }   // returning false == user cancel
        let r = try drive(config(), keepGoing: cancelAfterFirst)
        print("  cancel: outcome.cancelled=\(r.outcome?.cancelled ?? false), error=\(String(describing: r.error))")
        let o = try XCTUnwrap(r.outcome, "cancel returns a cancelled outcome, not a throw")
        XCTAssertTrue(o.cancelled, "a cancelled remote run returns a cancelled outcome")
    }

    // MARK: handoff-101 liveness cases

    /// (a) slow_sparse — PROGRESS events arrive MINUTES apart (here: seconds, gap >
    /// the inactivity grace), and the worker's keepalive ping is the ONLY thing
    /// keeping the stream fresh in between. The run must COMPLETE — no wall-clock
    /// timeout, no spurious "unreachable" failure. This is the incident's exact
    /// shape (a big run whose iterations are slow) proven not to false-fail.
    private func runSlowSparseCompletes() throws {
        let start = Date()
        let r = try drive(config(), timeout: 60)
        let elapsed = Date().timeIntervalSince(start)
        print("  slow_sparse: elapsed=\(String(format: "%.1f", elapsed))s streamed=\(r.streamed) "
            + "progress=\(r.progress) error=\(String(describing: r.error))")
        XCTAssertNil(r.error, "a progressing-but-slow run must not fail (no wall clock)")
        let o = try XCTUnwrap(r.outcome)
        XCTAssertEqual(o.acceptedCount, 2, "both variants complete despite the sparse cadence")
        XCTAssertGreaterThan(elapsed, inactivityGrace,
                             "the run genuinely outlived the inactivity grace (heartbeat carried it)")
    }

    /// (b) stream_drop — a recording proxy severs the SSE stream mid-run. The client
    /// must RECONNECT, DEDUPE the worker's from-the-start replay (variant count
    /// correct, no duplicate onVariant), and complete. If dedup were broken, the
    /// replayed first variant would fire onVariant a second time → streamed == 3.
    private func runStreamDropReconnects() throws {
        let r = try drive(config(), timeout: 60)
        print("  stream_drop: streamed=\(r.streamed) progress=\(r.progress) "
            + "error=\(String(describing: r.error))")
        XCTAssertNil(r.error, "a dropped stream is recoverable, not terminal")
        let o = try XCTUnwrap(r.outcome)
        XCTAssertEqual(o.acceptedCount, 2, "exactly two variants after the reconnect+dedup")
        XCTAssertEqual(r.streamed, 2, "onVariant fired once per variant — the replay was deduped")
    }

    /// (c) worker_dies_midrun — the worker PROCESS is killed mid-run. The inactivity
    /// watchdog probes, finds the worker unreachable, and fails with the
    /// worker-unreachable message (NOT "timed out"). Crucially it must NOT have sent
    /// a DELETE — the Mac's job is never destroyed by a liveness failure. The
    /// recording proxy's request log proves no DELETE crossed the wire.
    private func runWorkerDiesUnreachable() throws {
        let r = try drive(config(), timeout: 60)
        let err = try XCTUnwrap(r.error, "a dead worker must surface a failure, not hang")
        let msg = "\(err)"
        print("  worker_dies: failure=\(msg)")
        XCTAssertNil(r.outcome, "no outcome when the worker vanished")
        XCTAssertTrue(msg.lowercased().contains("unreachable") || msg.contains("Mac worker"),
                      "message names the worker as unreachable, not a timeout")
        XCTAssertFalse(msg.lowercased().contains("timed out"), "must NOT read as a timeout")

        // The cardinal rule: NEVER cancel the Mac's job except on explicit user
        // cancel. The proxy recorded every request the client made — assert none was
        // a DELETE.
        if let logPath = proxyLogPath, let log = try? String(contentsOfFile: logPath, encoding: .utf8) {
            let deletes = log.split(separator: "\n").filter { $0.hasPrefix("DELETE") }
            print("  proxy saw \(log.split(separator: "\n").count) request(s); DELETEs: \(deletes.count)")
            XCTAssertTrue(deletes.isEmpty, "NO DELETE may be sent when the worker dies — the Mac keeps its work")
        } else {
            XCTFail("worker_dies needs the proxy request log (TOPOPT_PROXY_LOG) to assert no DELETE")
        }
    }
}

/// Observes a RunModel's @Published state on the main actor (Combine sink).
@MainActor
private final class Observer {
    private var cancellables: [Any] = []
    init(model: RunModel, _ onChange: @escaping (RunPhase, RunProgress?, OptimizeOutcome?) -> Void) {
        // Poll via a lightweight timer: RunModel's fields are @Published but this
        // avoids importing Combine plumbing; a 20ms cadence is ample for the test.
        let t = Timer.scheduledTimer(withTimeInterval: 0.02, repeats: true) { _ in
            Task { @MainActor in onChange(model.phase, model.progress, model.outcome) }
        }
        cancellables.append(t)
    }
    func stop() { for c in cancellables { (c as? Timer)?.invalidate() } }
}
