// Unit tests for the 8-node hexahedral element stiffness matrix (ROADMAP M2.1).
//
// No third-party test framework is available (ARCHITECTURE §4 locks the
// dependency set), so this reuses the self-contained CHECK harness style from
// the other unit tests and exercises the public API only (topopt/fea.hpp).
//
// Ground truth is the human-authored reference fixture
// core/tests/fixtures/fea/hex_stiffness_reference.json (DECISIONS.md
// 2026-07-04: generated by the maintainer's reviewer via an independent
// NumPy implementation). It holds the exact 24x24 stiffness matrix for a UNIT
// cube (edge h=1, E=1) at two Poisson ratios, with a stated entrywise
// comparison tolerance. This test asserts against those values; it does not
// edit the fixture. The JSON reader below is a deliberately test-scoped subset
// parser (objects/arrays/strings/numbers) — not a public library API.

#include "topopt/fea.hpp"

#include <array>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

using topopt::Hex8Stiffness;
using topopt::hex8_stiffness;

static int g_failures = 0;
static int g_checks = 0;

#define CHECK(cond, msg)                                            \
  do {                                                             \
    ++g_checks;                                                    \
    if (!(cond)) {                                                 \
      ++g_failures;                                                \
      std::fprintf(stderr, "FAIL (line %d): %s\n", __LINE__, msg); \
    }                                                              \
  } while (0)

namespace {

// --- Minimal, test-local JSON reader --------------------------------------
// The reference fixture is clean, machine-generated JSON. This parses exactly
// the object / array / string / number subset it uses (numbers include signs
// and scientific notation). It is intentionally not a public API.
struct Json {
  enum class T { Num, Str, Arr, Obj } t = T::Num;
  double num = 0.0;
  std::string str;
  std::vector<Json> arr;
  std::vector<std::pair<std::string, Json>> obj;

  const Json& at(const std::string& key) const {
    for (const auto& kv : obj)
      if (kv.first == key) return kv.second;
    throw std::runtime_error("missing JSON key: " + key);
  }
};

class JsonParser {
 public:
  explicit JsonParser(const std::string& s) : s_(s) {}
  Json parse() {
    skip_ws();
    Json v = value();
    skip_ws();
    if (pos_ != s_.size()) throw std::runtime_error("trailing JSON characters");
    return v;
  }

 private:
  const std::string& s_;
  std::size_t pos_ = 0;

  void skip_ws() {
    while (pos_ < s_.size()) {
      char c = s_[pos_];
      if (c == ' ' || c == '\t' || c == '\n' || c == '\r') ++pos_;
      else break;
    }
  }
  char peek() {
    if (pos_ >= s_.size()) throw std::runtime_error("unexpected end of JSON");
    return s_[pos_];
  }
  Json value() {
    skip_ws();
    char c = peek();
    if (c == '{') return object();
    if (c == '[') return array();
    if (c == '"') {
      Json v;
      v.t = Json::T::Str;
      v.str = string();
      return v;
    }
    if (c == '-' || (c >= '0' && c <= '9')) return number();
    throw std::runtime_error(std::string("unexpected JSON character '") + c +
                             "'");
  }
  Json object() {
    Json v;
    v.t = Json::T::Obj;
    ++pos_;  // '{'
    skip_ws();
    if (peek() == '}') {
      ++pos_;
      return v;
    }
    while (true) {
      skip_ws();
      if (peek() != '"') throw std::runtime_error("expected JSON object key");
      std::string key = string();
      skip_ws();
      if (peek() != ':') throw std::runtime_error("expected ':' in object");
      ++pos_;
      v.obj.emplace_back(std::move(key), value());
      skip_ws();
      char n = peek();
      ++pos_;
      if (n == ',') continue;
      if (n == '}') break;
      throw std::runtime_error("expected ',' or '}' in object");
    }
    return v;
  }
  Json array() {
    Json v;
    v.t = Json::T::Arr;
    ++pos_;  // '['
    skip_ws();
    if (peek() == ']') {
      ++pos_;
      return v;
    }
    while (true) {
      v.arr.push_back(value());
      skip_ws();
      char n = peek();
      ++pos_;
      if (n == ',') continue;
      if (n == ']') break;
      throw std::runtime_error("expected ',' or ']' in array");
    }
    return v;
  }
  Json number() {
    std::size_t start = pos_;
    if (peek() == '-') ++pos_;
    while (pos_ < s_.size()) {
      char c = s_[pos_];
      if ((c >= '0' && c <= '9') || c == '.' || c == 'e' || c == 'E' ||
          c == '+' || c == '-')
        ++pos_;
      else
        break;
    }
    Json v;
    v.t = Json::T::Num;
    v.num = std::stod(s_.substr(start, pos_ - start));
    return v;
  }
  std::string string() {
    ++pos_;  // opening quote
    std::string out;
    while (true) {
      if (pos_ >= s_.size()) throw std::runtime_error("unterminated string");
      char c = s_[pos_++];
      if (c == '"') break;
      if (c == '\\') {
        if (pos_ >= s_.size()) throw std::runtime_error("unterminated escape");
        char e = s_[pos_++];
        switch (e) {
          case '"': out.push_back('"'); break;
          case '\\': out.push_back('\\'); break;
          case '/': out.push_back('/'); break;
          case 'n': out.push_back('\n'); break;
          case 't': out.push_back('\t'); break;
          default: out.push_back(e); break;  // fixture uses no exotic escapes
        }
      } else {
        out.push_back(c);
      }
    }
    return out;
  }
};

Json load_json(const std::string& path) {
  std::ifstream in(path, std::ios::binary);
  if (!in) throw std::runtime_error("cannot open fixture: " + path);
  std::ostringstream ss;
  ss << in.rdbuf();
  return JsonParser(ss.str()).parse();
}

// Read the fixture's 24x24 "K" array into a flat row-major buffer.
std::array<double, 576> read_matrix(const Json& k) {
  std::array<double, 576> m{};
  if (k.arr.size() != 24) throw std::runtime_error("K is not 24 rows");
  for (int r = 0; r < 24; ++r) {
    if (k.arr[r].arr.size() != 24) throw std::runtime_error("K row not 24 wide");
    for (int c = 0; c < 24; ++c)
      m[static_cast<std::size_t>(r) * 24 + c] = k.arr[r].arr[c].num;
  }
  return m;
}

double max_abs(const std::array<double, 576>& m) {
  double mx = 0.0;
  for (double v : m) mx = std::max(mx, std::fabs(v));
  return mx;
}

}  // namespace

int main() {
  const std::string path =
      std::string(FEA_FIXTURE_DIR) + "/hex_stiffness_reference.json";
  Json root = load_json(path);
  const Json& cases = root.at("cases");

  struct CaseSpec {
    const char* key;
    double E;
    double nu;
  };
  // Both fixture cases are the unit cube (E=1, h=1) — see the fixture's
  // "scaling" note. Values from each case's "youngs_modulus"/"poisson".
  const CaseSpec specs[] = {{"E1_nu0.30", 1.0, 0.3}, {"E1_nu0.40", 1.0, 0.4}};

  for (const CaseSpec& cs : specs) {
    const Json& c = cases.at(cs.key);
    // The fixture states E and nu explicitly; assert we drive the element with
    // the same numbers it was generated for.
    CHECK(c.at("youngs_modulus").num == cs.E, "fixture youngs_modulus matches");
    CHECK(c.at("poisson").num == cs.nu, "fixture poisson matches");

    const std::array<double, 576> ref = read_matrix(c.at("K"));
    const double ref_max = max_abs(ref);
    // Fixture "comparison_tolerance": |K_ij - ref_ij| <= 1e-10 * max|ref|.
    const double tol = 1e-10 * ref_max;

    // Unit cube (h = 1) to match the fixture exactly.
    const Hex8Stiffness Ke = hex8_stiffness(cs.E, cs.nu, 1.0);

    // --- Entrywise agreement with the independent reference matrix ---------
    double worst = 0.0;
    int violations = 0;
    for (int r = 0; r < 24; ++r)
      for (int col = 0; col < 24; ++col) {
        double d = std::fabs(Ke(r, col) - ref[static_cast<std::size_t>(r) * 24 + col]);
        worst = std::max(worst, d);
        if (d > tol) ++violations;
      }
    CHECK(violations == 0, "every K entry matches the reference within tol");
    CHECK(worst <= tol, "worst-case entry error within fixture tolerance");

    // --- Symmetry: max|K - K^T| <= 1e-12 * max|K| --------------------------
    double k_max = 0.0;
    for (int r = 0; r < 24; ++r)
      for (int col = 0; col < 24; ++col)
        k_max = std::max(k_max, std::fabs(Ke(r, col)));
    double sym_err = 0.0;
    for (int r = 0; r < 24; ++r)
      for (int col = 0; col < 24; ++col)
        sym_err = std::max(sym_err, std::fabs(Ke(r, col) - Ke(col, r)));
    CHECK(sym_err <= 1e-12 * k_max, "element stiffness is symmetric");

    // --- Rigid translation null space: K @ t = 0 for a unit translation of
    // every node along x, y, z (3 of the 6 zero-energy modes). --------------
    for (int axis = 0; axis < 3; ++axis) {
      double resid = 0.0;
      for (int r = 0; r < 24; ++r) {
        double s = 0.0;
        for (int node = 0; node < 8; ++node) s += Ke(r, 3 * node + axis);
        resid = std::max(resid, std::fabs(s));
      }
      CHECK(resid <= 1e-12 * k_max,
            "unit rigid translation is in the null space");
    }

    // --- Scaling law: K(E, h) = E * h * K(1, 1) for fixed nu ----------------
    // Drive with a distinctly different modulus and (still cubic) voxel edge
    // and compare against E*h*ref entrywise.
    const double E2 = 210000.0;  // MPa-scale, arbitrary but far from 1
    const double h2 = 0.5;
    const Hex8Stiffness Ke2 = hex8_stiffness(E2, cs.nu, h2);
    double scale_worst = 0.0;
    const double scale_tol = 1e-9 * (E2 * h2 * ref_max);
    for (int r = 0; r < 24; ++r)
      for (int col = 0; col < 24; ++col) {
        double expected = E2 * h2 * ref[static_cast<std::size_t>(r) * 24 + col];
        scale_worst = std::max(scale_worst, std::fabs(Ke2(r, col) - expected));
      }
    CHECK(scale_worst <= scale_tol, "K(E,h) = E*h*K_ref within tolerance");
  }

  // ==========================================================================
  // hex8_stress: element stress recovery from nodal displacements (M2.4). Impose
  // known uniform-strain fields on a unit-cube element and check the recovered
  // Cauchy stress and von Mises against closed form. A linear displacement field
  // gives constant strain, so the centroid sample is exact. Node local coords
  // (edge h=1) follow the Hex8 order documented in fea.hpp.
  // ==========================================================================
  {
    using topopt::Hex8Stress;
    using topopt::hex8_stress;
    const double X[8] = {0, 1, 1, 0, 0, 1, 1, 0};
    const double Y[8] = {0, 0, 1, 1, 0, 0, 1, 1};
    const double E = 200.0, nu = 0.3, h = 1.0;
    const double c = E / ((1.0 + nu) * (1.0 - 2.0 * nu));
    const double G = E / (2.0 * (1.0 + nu));
    auto approx = [](double a, double b, double tol) {
      return std::fabs(a - b) <= tol;
    };

    // (a) Uniaxial STRAIN field u_x = a*X  (eps_xx = a, all other strains 0).
    {
      const double a = 1e-3;
      std::array<double, 24> ue{};
      for (int n = 0; n < 8; ++n) ue[static_cast<std::size_t>(3 * n)] = a * X[n];
      const Hex8Stress st = hex8_stress(E, nu, h, ue);
      const double sxx = c * (1.0 - nu) * a;
      const double syy = c * nu * a;  // = szz
      const double s = 1e-9 * std::fabs(sxx);
      CHECK(approx(st.sigma[0], sxx, s), "uniaxial-strain: sxx = c(1-nu)eps");
      CHECK(approx(st.sigma[1], syy, s), "uniaxial-strain: syy = c*nu*eps");
      CHECK(approx(st.sigma[2], syy, s), "uniaxial-strain: szz = c*nu*eps");
      CHECK(approx(st.sigma[3], 0.0, s) && approx(st.sigma[4], 0.0, s) &&
                approx(st.sigma[5], 0.0, s),
            "uniaxial-strain: shear stresses zero");
      const double vm = std::fabs(sxx - syy);  // syy=szz, shears 0
      CHECK(approx(st.von_mises, vm, 1e-9 * vm),
            "uniaxial-strain: von Mises = |sxx - syy|");
    }

    // (b) Pure shear field u_x = g*Y  (engineering gamma_xy = g, others 0).
    {
      const double g = 2e-3;
      std::array<double, 24> ue{};
      for (int n = 0; n < 8; ++n) ue[static_cast<std::size_t>(3 * n)] = g * Y[n];
      const Hex8Stress st = hex8_stress(E, nu, h, ue);
      const double sxy = G * g;
      const double s = 1e-9 * std::fabs(sxy);
      CHECK(approx(st.sigma[0], 0.0, s) && approx(st.sigma[1], 0.0, s) &&
                approx(st.sigma[2], 0.0, s),
            "pure-shear: normal stresses zero");
      CHECK(approx(st.sigma[3], sxy, s), "pure-shear: sxy = G*gamma");
      CHECK(approx(st.sigma[4], 0.0, s) && approx(st.sigma[5], 0.0, s),
            "pure-shear: other shear stresses zero");
      const double vm = std::sqrt(3.0) * std::fabs(sxy);
      CHECK(approx(st.von_mises, vm, 1e-9 * vm),
            "pure-shear: von Mises = sqrt(3)|sxy|");
    }

    // (c) Rigid translation of all nodes -> zero strain -> zero stress.
    {
      std::array<double, 24> ue{};
      for (int n = 0; n < 8; ++n) {
        ue[static_cast<std::size_t>(3 * n + 0)] = 0.7;
        ue[static_cast<std::size_t>(3 * n + 1)] = -0.3;
        ue[static_cast<std::size_t>(3 * n + 2)] = 1.1;
      }
      const Hex8Stress st = hex8_stress(E, nu, h, ue);
      double mx = 0.0;
      for (double sv : st.sigma) mx = std::max(mx, std::fabs(sv));
      CHECK(mx <= 1e-9 && st.von_mises <= 1e-9,
            "rigid translation gives zero stress");
    }

    // (d) Argument validation mirrors hex8_stiffness.
    {
      std::array<double, 24> ue{};
      auto throws_s = [&](double E_, double nu_, double h_) {
        try {
          hex8_stress(E_, nu_, h_, ue);
        } catch (const std::invalid_argument&) {
          return true;
        }
        return false;
      };
      CHECK(throws_s(0.0, 0.3, 1.0), "stress: E == 0 rejected");
      CHECK(throws_s(1.0, 0.5, 1.0), "stress: poisson == 0.5 rejected");
      CHECK(throws_s(1.0, 0.3, 0.0), "stress: element_size == 0 rejected");
    }
  }

  // ==========================================================================
  // hex8_stiffness_transverse: transversely isotropic element (M4.1). Layer
  // plane = xy, layer-normal (build) axis = z, knocked down by k = z_knockdown.
  //
  // The 6x6 constitutive matrix D is recovered from the element stiffness Ke
  // without any private API: a uniform (constant) strain field eps applied as
  // nodal displacements u = eps . x is represented exactly by the trilinear
  // element, so its strain energy is 0.5 * Vol * eps^T D eps = 0.5 * u^T Ke u.
  // With Vol = h^3 this gives the quadratic form q(eps) = eps^T D eps =
  // (u^T Ke u)/h^3, from which every D entry follows:
  //   D_ii = q(e_i),  D_ij = (q(e_i+e_j) - q(e_i) - q(e_j)) / 2.
  // ==========================================================================
  {
    using topopt::hex8_stiffness_transverse;

    // Unit-cube node coordinates (edge h = 1), Hex8 order per fea.hpp.
    const double NX[8] = {0, 1, 1, 0, 0, 1, 1, 0};
    const double NY[8] = {0, 0, 1, 1, 0, 0, 1, 1};
    const double NZ[8] = {0, 0, 0, 0, 1, 1, 1, 1};

    // q(eps) = eps^T D eps recovered from Ke via a uniform-strain nodal field
    // (h = 1, so Vol = 1). eps is Voigt [xx,yy,zz,gxy,gyz,gzx], engineering
    // shear (tensor off-diagonals are half the engineering shear).
    auto qform = [&](const Hex8Stiffness& Ke, const double eps[6]) {
      const double exx = eps[0], eyy = eps[1], ezz = eps[2];
      const double exy = 0.5 * eps[3], eyz = 0.5 * eps[4], ezx = 0.5 * eps[5];
      std::array<double, 24> u{};
      for (int n = 0; n < 8; ++n) {
        const double x = NX[n], y = NY[n], z = NZ[n];
        u[static_cast<std::size_t>(3 * n + 0)] = exx * x + exy * y + ezx * z;
        u[static_cast<std::size_t>(3 * n + 1)] = exy * x + eyy * y + eyz * z;
        u[static_cast<std::size_t>(3 * n + 2)] = ezx * x + eyz * y + ezz * z;
      }
      double q = 0.0;
      for (int r = 0; r < 24; ++r) {
        double s = 0.0;
        for (int col = 0; col < 24; ++col)
          s += Ke(r, col) * u[static_cast<std::size_t>(col)];
        q += u[static_cast<std::size_t>(r)] * s;
      }
      return q;  // Vol = h^3 = 1
    };

    // Recover the full symmetric 6x6 D from Ke.
    auto recover_D = [&](const Hex8Stiffness& Ke, double D[6][6]) {
      double qi[6];
      for (int i = 0; i < 6; ++i) {
        double e[6] = {};
        e[i] = 1.0;
        qi[i] = qform(Ke, e);
        D[i][i] = qi[i];
      }
      for (int i = 0; i < 6; ++i)
        for (int j = i + 1; j < 6; ++j) {
          double e[6] = {};
          e[i] = 1.0;
          e[j] = 1.0;
          const double dij = 0.5 * (qform(Ke, e) - qi[i] - qi[j]);
          D[i][j] = dij;
          D[j][i] = dij;
        }
    };

    const double E = 3500.0, nu = 0.33;  // PLA-scale, ARCHITECTURE §6 seed
    const double c = E / ((1.0 + nu) * (1.0 - 2.0 * nu));
    const double G = E / (2.0 * (1.0 + nu));

    // (a) Reconstruction sanity: the isotropic element recovers the isotropic D.
    {
      double Diso[6][6];
      recover_D(hex8_stiffness(E, nu, 1.0), Diso);
      const double t = 1e-8 * c;
      CHECK(std::fabs(Diso[0][0] - c * (1.0 - nu)) <= t &&
                std::fabs(Diso[2][2] - c * (1.0 - nu)) <= t,
            "recover_D: isotropic normal-diagonal = c(1-nu)");
      CHECK(std::fabs(Diso[0][1] - c * nu) <= t &&
                std::fabs(Diso[0][2] - c * nu) <= t,
            "recover_D: isotropic normal-offdiagonal = c*nu");
      CHECK(std::fabs(Diso[3][3] - G) <= t && std::fabs(Diso[4][4] - G) <= t &&
                std::fabs(Diso[5][5] - G) <= t,
            "recover_D: isotropic shear-diagonal = G");
    }

    // (b) z_knockdown = 1.0 reproduces the isotropic element entrywise.
    {
      const Hex8Stiffness Ki = hex8_stiffness(E, nu, 1.0);
      const Hex8Stiffness Kt = hex8_stiffness_transverse(E, nu, 1.0, 1.0);
      double kmax = 0.0, worst = 0.0;
      for (int r = 0; r < 24; ++r)
        for (int col = 0; col < 24; ++col) {
          kmax = std::max(kmax, std::fabs(Ki(r, col)));
          worst = std::max(worst, std::fabs(Ki(r, col) - Kt(r, col)));
        }
      CHECK(worst <= 1e-9 * kmax,
            "z_knockdown=1 reproduces isotropic element (isotropic mode)");
    }

    // (c) Knocked-down element (k = 0.55, PLA seed): transverse-isotropic
    // structure of D, in-plane block preserved, z + transverse shears softened.
    {
      const double k = 0.55;
      double Di[6][6], Dt[6][6];
      recover_D(hex8_stiffness(E, nu, 1.0), Di);
      recover_D(hex8_stiffness_transverse(E, nu, 1.0, k), Dt);
      const double t = 1e-7 * c;

      // Symmetry about the z axis: (x,y) interchangeable.
      CHECK(std::fabs(Dt[0][0] - Dt[1][1]) <= t &&
                std::fabs(Dt[0][2] - Dt[1][2]) <= t &&
                std::fabs(Dt[0][2] - Dt[2][0]) <= t,
            "transverse: D is symmetric about the z (layer-normal) axis");

      // In-plane shear (xy) unchanged; transverse shears (yz, zx) = k * G.
      CHECK(std::fabs(Dt[3][3] - G) <= t, "transverse: G_xy unchanged (= G)");
      CHECK(std::fabs(Dt[4][4] - k * G) <= t &&
                std::fabs(Dt[5][5] - k * G) <= t,
            "transverse: G_yz = G_zx = k * G");

      // z-normal stiffness strictly softer than isotropic; z != in-plane.
      CHECK(Dt[2][2] < Di[2][2] - t, "transverse: D_zz softened below isotropic");
      CHECK(Dt[2][2] < Dt[0][0] - t, "transverse: D_zz < D_xx (anisotropic)");

      // Engineering constants from the compliance S = N^{-1} of the normal
      // block N = [[a,b,c],[b,a,c],[c,c,d]] (a=Dxx,b=Dxy,c=Dxz,d=Dzz):
      //   E_x = 1/S_xx,  E_z = 1/S_zz,  nu_xy = -S_xy/S_xx.
      const double a = Dt[0][0], b = Dt[0][1], cc = Dt[0][2], d = Dt[2][2];
      const double det = a * (a * d - cc * cc) - b * (b * d - cc * cc) +
                         cc * (b * cc - a * cc);
      const double Sxx = (a * d - cc * cc) / det;
      const double Szz = (a * a - b * b) / det;
      const double Sxy = -(b * d - cc * cc) / det;
      const double Ex = 1.0 / Sxx, Ez = 1.0 / Szz, nuxy = -Sxy / Sxx;
      CHECK(std::fabs(Ex - E) <= 1e-6 * E, "transverse: in-plane E_x = E");
      CHECK(std::fabs(Ez - k * E) <= 1e-6 * E,
            "transverse: z-axis E_z = k * E (the knockdown)");
      CHECK(std::fabs(nuxy - nu) <= 1e-7, "transverse: in-plane nu_xy = nu");
    }

    // (d) Scaling law K(E,h,k) = E*h*K(1,1,k) for fixed nu, k (as isotropic).
    {
      const double k = 0.7;  // PETG seed
      const double E2 = 210000.0, h2 = 0.5;
      const Hex8Stiffness Ku = hex8_stiffness_transverse(1.0, nu, 1.0, k);
      const Hex8Stiffness Ks = hex8_stiffness_transverse(E2, nu, h2, k);
      double umax = 0.0, worst = 0.0;
      for (int r = 0; r < 24; ++r)
        for (int col = 0; col < 24; ++col) {
          umax = std::max(umax, std::fabs(Ku(r, col)));
          worst = std::max(worst, std::fabs(Ks(r, col) - E2 * h2 * Ku(r, col)));
        }
      CHECK(worst <= 1e-9 * (E2 * h2 * umax),
            "transverse: K(E,h,k) = E*h*K(1,1,k)");
    }

    // (e) Argument validation: material checks mirror hex8_stiffness, plus the
    // z_knockdown range (0, 1].
    {
      auto throws_t = [](double E_, double nu_, double h_, double k_) {
        try {
          hex8_stiffness_transverse(E_, nu_, h_, k_);
        } catch (const std::invalid_argument&) {
          return true;
        }
        return false;
      };
      CHECK(throws_t(0.0, 0.3, 1.0, 0.5), "transverse: E == 0 rejected");
      CHECK(throws_t(1.0, 0.5, 1.0, 0.5), "transverse: poisson == 0.5 rejected");
      CHECK(throws_t(1.0, 0.3, 0.0, 0.5), "transverse: element_size == 0 rejected");
      CHECK(throws_t(1.0, 0.3, 1.0, 0.0), "transverse: z_knockdown == 0 rejected");
      CHECK(throws_t(1.0, 0.3, 1.0, -0.1), "transverse: negative z_knockdown rejected");
      CHECK(throws_t(1.0, 0.3, 1.0, 1.5), "transverse: z_knockdown > 1 rejected");
      bool ok = true;
      try {
        hex8_stiffness_transverse(1.0, 0.3, 1.0, 1.0);
      } catch (...) {
        ok = false;
      }
      CHECK(ok, "transverse: z_knockdown == 1 accepted");
    }
  }

  // ==========================================================================
  // hex8_stiffness_transverse vs the independent golden fixture (M4.1). The
  // file core/tests/fixtures/fea/hex_stiffness_ti_reference.json holds reference
  // stiffness matrices for the transversely isotropic element on a UNIT CUBE
  // (edge h=1), authored by the maintainer via an independent NumPy
  // implementation (same provenance/discipline as the isotropic fixture). Its
  // locked mapping (E_t=k*E0, nu_pt=nu, G_t=k*G_p, layer normal +Z) is exactly
  // the one hex8_stiffness_transverse implements. Assert entrywise agreement for
  // all three committed cases at the fixture's stated comparison_tolerance, plus
  // the required_properties isotropic-reduction clause. This test reads the
  // fixture; it does not edit it.
  // ==========================================================================
  {
    using topopt::hex8_stiffness_transverse;
    const std::string ti_path =
        std::string(FEA_FIXTURE_DIR) + "/hex_stiffness_ti_reference.json";
    Json ti_root = load_json(ti_path);
    const Json& ti_cases = ti_root.at("cases");

    struct TiSpec {
      const char* key;
      double E;
      double nu;
      double k;
    };
    // The three committed cases; each is the unit cube (E=1, h=1). Values from
    // each case's youngs_modulus / poisson / z_knockdown.
    const TiSpec ti_specs[] = {
        {"E1_nu0.30_k0.55", 1.0, 0.30, 0.55},
        {"E1_nu0.30_k1.00", 1.0, 0.30, 1.00},
        {"E1_nu0.35_k0.70", 1.0, 0.35, 0.70},
    };

    for (const TiSpec& ts : ti_specs) {
      const Json& c = ti_cases.at(ts.key);
      // Assert we drive the element with the numbers the fixture was generated
      // for (E, nu, k).
      CHECK(c.at("youngs_modulus").num == ts.E,
            "TI fixture youngs_modulus matches");
      CHECK(c.at("poisson").num == ts.nu, "TI fixture poisson matches");
      CHECK(c.at("z_knockdown").num == ts.k, "TI fixture z_knockdown matches");

      const std::array<double, 576> ref = read_matrix(c.at("K"));
      const double ref_max = max_abs(ref);
      // Fixture "comparison_tolerance": |K_ij - ref_ij| <= 1e-10 * max|ref|.
      const double tol = 1e-10 * ref_max;

      const Hex8Stiffness Ke = hex8_stiffness_transverse(ts.E, ts.nu, 1.0, ts.k);
      double worst = 0.0;
      int violations = 0;
      for (int r = 0; r < 24; ++r)
        for (int col = 0; col < 24; ++col) {
          double d = std::fabs(Ke(r, col) -
                               ref[static_cast<std::size_t>(r) * 24 + col]);
          worst = std::max(worst, d);
          if (d > tol) ++violations;
        }
      CHECK(violations == 0, "TI: every K entry matches the reference within tol");
      CHECK(worst <= tol, "TI: worst-case entry error within fixture tolerance");
    }

    // required_properties.isotropic_reduction: "K(E,nu,k=1,h) equals the
    // isotropic element K(E,nu,h) entrywise within 1e-12 * max|K| — this is what
    // preserves Gate V1 in isotropic mode." Assert the k=1.00 case against the
    // ISOTROPIC hex8_stiffness for the same (E, nu, h).
    {
      const Hex8Stiffness Kt = hex8_stiffness_transverse(1.0, 0.30, 1.0, 1.00);
      const Hex8Stiffness Ki = hex8_stiffness(1.0, 0.30, 1.0);
      double kmax = 0.0, worst = 0.0;
      for (int r = 0; r < 24; ++r)
        for (int col = 0; col < 24; ++col) {
          kmax = std::max(kmax, std::fabs(Ki(r, col)));
          worst = std::max(worst, std::fabs(Kt(r, col) - Ki(r, col)));
        }
      CHECK(worst <= 1e-12 * kmax,
            "TI: k=1 reduces to the isotropic element within 1e-12*max|K|");
    }
  }

  // --- Argument validation ---------------------------------------------------
  {
    auto throws = [](double E, double nu, double h) {
      try {
        hex8_stiffness(E, nu, h);
      } catch (const std::invalid_argument&) {
        return true;
      }
      return false;
    };
    CHECK(throws(0.0, 0.3, 1.0), "E == 0 rejected");
    CHECK(throws(-1.0, 0.3, 1.0), "negative E rejected");
    CHECK(throws(1.0, 0.5, 1.0), "poisson == 0.5 rejected (incompressible)");
    CHECK(throws(1.0, 0.6, 1.0), "poisson > 0.5 rejected");
    CHECK(throws(1.0, 0.3, 0.0), "element_size == 0 rejected");
    CHECK(throws(1.0, 0.3, -2.0), "negative element_size rejected");
    // A valid call does not throw.
    bool ok = true;
    try {
      hex8_stiffness(1.0, 0.3, 1.0);
    } catch (...) {
      ok = false;
    }
    CHECK(ok, "valid arguments do not throw");
  }

  if (g_failures == 0) {
    std::printf("hex element: all %d checks passed\n", g_checks);
    return 0;
  }
  std::fprintf(stderr, "hex element: %d/%d checks FAILED\n", g_failures,
               g_checks);
  return 1;
}
