// Unit tests for the 8-node hexahedral element stiffness matrix (ROADMAP M2.1).
//
// No third-party test framework is available (ARCHITECTURE §4 locks the
// dependency set), so this reuses the self-contained CHECK harness style from
// the other unit tests and exercises the public API only (topopt/fea.hpp).
//
// Ground truth is the human-authored reference fixture
// core/tests/fixtures/fea/hex_stiffness_reference.json (DECISIONS.md
// 2026-07-04: generated by the maintainer's reviewer via an independent
// NumPy implementation). It holds the exact 24x24 stiffness matrix for a UNIT
// cube (edge h=1, E=1) at two Poisson ratios, with a stated entrywise
// comparison tolerance. This test asserts against those values; it does not
// edit the fixture. The JSON reader below is a deliberately test-scoped subset
// parser (objects/arrays/strings/numbers) — not a public library API.

#include "topopt/fea.hpp"

#include <array>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

using topopt::Hex8Stiffness;
using topopt::hex8_stiffness;

static int g_failures = 0;
static int g_checks = 0;

#define CHECK(cond, msg)                                            \
  do {                                                             \
    ++g_checks;                                                    \
    if (!(cond)) {                                                 \
      ++g_failures;                                                \
      std::fprintf(stderr, "FAIL (line %d): %s\n", __LINE__, msg); \
    }                                                              \
  } while (0)

namespace {

// --- Minimal, test-local JSON reader --------------------------------------
// The reference fixture is clean, machine-generated JSON. This parses exactly
// the object / array / string / number subset it uses (numbers include signs
// and scientific notation). It is intentionally not a public API.
struct Json {
  enum class T { Num, Str, Arr, Obj } t = T::Num;
  double num = 0.0;
  std::string str;
  std::vector<Json> arr;
  std::vector<std::pair<std::string, Json>> obj;

  const Json& at(const std::string& key) const {
    for (const auto& kv : obj)
      if (kv.first == key) return kv.second;
    throw std::runtime_error("missing JSON key: " + key);
  }
};

class JsonParser {
 public:
  explicit JsonParser(const std::string& s) : s_(s) {}
  Json parse() {
    skip_ws();
    Json v = value();
    skip_ws();
    if (pos_ != s_.size()) throw std::runtime_error("trailing JSON characters");
    return v;
  }

 private:
  const std::string& s_;
  std::size_t pos_ = 0;

  void skip_ws() {
    while (pos_ < s_.size()) {
      char c = s_[pos_];
      if (c == ' ' || c == '\t' || c == '\n' || c == '\r') ++pos_;
      else break;
    }
  }
  char peek() {
    if (pos_ >= s_.size()) throw std::runtime_error("unexpected end of JSON");
    return s_[pos_];
  }
  Json value() {
    skip_ws();
    char c = peek();
    if (c == '{') return object();
    if (c == '[') return array();
    if (c == '"') {
      Json v;
      v.t = Json::T::Str;
      v.str = string();
      return v;
    }
    if (c == '-' || (c >= '0' && c <= '9')) return number();
    throw std::runtime_error(std::string("unexpected JSON character '") + c +
                             "'");
  }
  Json object() {
    Json v;
    v.t = Json::T::Obj;
    ++pos_;  // '{'
    skip_ws();
    if (peek() == '}') {
      ++pos_;
      return v;
    }
    while (true) {
      skip_ws();
      if (peek() != '"') throw std::runtime_error("expected JSON object key");
      std::string key = string();
      skip_ws();
      if (peek() != ':') throw std::runtime_error("expected ':' in object");
      ++pos_;
      v.obj.emplace_back(std::move(key), value());
      skip_ws();
      char n = peek();
      ++pos_;
      if (n == ',') continue;
      if (n == '}') break;
      throw std::runtime_error("expected ',' or '}' in object");
    }
    return v;
  }
  Json array() {
    Json v;
    v.t = Json::T::Arr;
    ++pos_;  // '['
    skip_ws();
    if (peek() == ']') {
      ++pos_;
      return v;
    }
    while (true) {
      v.arr.push_back(value());
      skip_ws();
      char n = peek();
      ++pos_;
      if (n == ',') continue;
      if (n == ']') break;
      throw std::runtime_error("expected ',' or ']' in array");
    }
    return v;
  }
  Json number() {
    std::size_t start = pos_;
    if (peek() == '-') ++pos_;
    while (pos_ < s_.size()) {
      char c = s_[pos_];
      if ((c >= '0' && c <= '9') || c == '.' || c == 'e' || c == 'E' ||
          c == '+' || c == '-')
        ++pos_;
      else
        break;
    }
    Json v;
    v.t = Json::T::Num;
    v.num = std::stod(s_.substr(start, pos_ - start));
    return v;
  }
  std::string string() {
    ++pos_;  // opening quote
    std::string out;
    while (true) {
      if (pos_ >= s_.size()) throw std::runtime_error("unterminated string");
      char c = s_[pos_++];
      if (c == '"') break;
      if (c == '\\') {
        if (pos_ >= s_.size()) throw std::runtime_error("unterminated escape");
        char e = s_[pos_++];
        switch (e) {
          case '"': out.push_back('"'); break;
          case '\\': out.push_back('\\'); break;
          case '/': out.push_back('/'); break;
          case 'n': out.push_back('\n'); break;
          case 't': out.push_back('\t'); break;
          default: out.push_back(e); break;  // fixture uses no exotic escapes
        }
      } else {
        out.push_back(c);
      }
    }
    return out;
  }
};

Json load_json(const std::string& path) {
  std::ifstream in(path, std::ios::binary);
  if (!in) throw std::runtime_error("cannot open fixture: " + path);
  std::ostringstream ss;
  ss << in.rdbuf();
  return JsonParser(ss.str()).parse();
}

// Read the fixture's 24x24 "K" array into a flat row-major buffer.
std::array<double, 576> read_matrix(const Json& k) {
  std::array<double, 576> m{};
  if (k.arr.size() != 24) throw std::runtime_error("K is not 24 rows");
  for (int r = 0; r < 24; ++r) {
    if (k.arr[r].arr.size() != 24) throw std::runtime_error("K row not 24 wide");
    for (int c = 0; c < 24; ++c)
      m[static_cast<std::size_t>(r) * 24 + c] = k.arr[r].arr[c].num;
  }
  return m;
}

double max_abs(const std::array<double, 576>& m) {
  double mx = 0.0;
  for (double v : m) mx = std::max(mx, std::fabs(v));
  return mx;
}

}  // namespace

int main() {
  const std::string path =
      std::string(FEA_FIXTURE_DIR) + "/hex_stiffness_reference.json";
  Json root = load_json(path);
  const Json& cases = root.at("cases");

  struct CaseSpec {
    const char* key;
    double E;
    double nu;
  };
  // Both fixture cases are the unit cube (E=1, h=1) — see the fixture's
  // "scaling" note. Values from each case's "youngs_modulus"/"poisson".
  const CaseSpec specs[] = {{"E1_nu0.30", 1.0, 0.3}, {"E1_nu0.40", 1.0, 0.4}};

  for (const CaseSpec& cs : specs) {
    const Json& c = cases.at(cs.key);
    // The fixture states E and nu explicitly; assert we drive the element with
    // the same numbers it was generated for.
    CHECK(c.at("youngs_modulus").num == cs.E, "fixture youngs_modulus matches");
    CHECK(c.at("poisson").num == cs.nu, "fixture poisson matches");

    const std::array<double, 576> ref = read_matrix(c.at("K"));
    const double ref_max = max_abs(ref);
    // Fixture "comparison_tolerance": |K_ij - ref_ij| <= 1e-10 * max|ref|.
    const double tol = 1e-10 * ref_max;

    // Unit cube (h = 1) to match the fixture exactly.
    const Hex8Stiffness Ke = hex8_stiffness(cs.E, cs.nu, 1.0);

    // --- Entrywise agreement with the independent reference matrix ---------
    double worst = 0.0;
    int violations = 0;
    for (int r = 0; r < 24; ++r)
      for (int col = 0; col < 24; ++col) {
        double d = std::fabs(Ke(r, col) - ref[static_cast<std::size_t>(r) * 24 + col]);
        worst = std::max(worst, d);
        if (d > tol) ++violations;
      }
    CHECK(violations == 0, "every K entry matches the reference within tol");
    CHECK(worst <= tol, "worst-case entry error within fixture tolerance");

    // --- Symmetry: max|K - K^T| <= 1e-12 * max|K| --------------------------
    double k_max = 0.0;
    for (int r = 0; r < 24; ++r)
      for (int col = 0; col < 24; ++col)
        k_max = std::max(k_max, std::fabs(Ke(r, col)));
    double sym_err = 0.0;
    for (int r = 0; r < 24; ++r)
      for (int col = 0; col < 24; ++col)
        sym_err = std::max(sym_err, std::fabs(Ke(r, col) - Ke(col, r)));
    CHECK(sym_err <= 1e-12 * k_max, "element stiffness is symmetric");

    // --- Rigid translation null space: K @ t = 0 for a unit translation of
    // every node along x, y, z (3 of the 6 zero-energy modes). --------------
    for (int axis = 0; axis < 3; ++axis) {
      double resid = 0.0;
      for (int r = 0; r < 24; ++r) {
        double s = 0.0;
        for (int node = 0; node < 8; ++node) s += Ke(r, 3 * node + axis);
        resid = std::max(resid, std::fabs(s));
      }
      CHECK(resid <= 1e-12 * k_max,
            "unit rigid translation is in the null space");
    }

    // --- Scaling law: K(E, h) = E * h * K(1, 1) for fixed nu ----------------
    // Drive with a distinctly different modulus and (still cubic) voxel edge
    // and compare against E*h*ref entrywise.
    const double E2 = 210000.0;  // MPa-scale, arbitrary but far from 1
    const double h2 = 0.5;
    const Hex8Stiffness Ke2 = hex8_stiffness(E2, cs.nu, h2);
    double scale_worst = 0.0;
    const double scale_tol = 1e-9 * (E2 * h2 * ref_max);
    for (int r = 0; r < 24; ++r)
      for (int col = 0; col < 24; ++col) {
        double expected = E2 * h2 * ref[static_cast<std::size_t>(r) * 24 + col];
        scale_worst = std::max(scale_worst, std::fabs(Ke2(r, col) - expected));
      }
    CHECK(scale_worst <= scale_tol, "K(E,h) = E*h*K_ref within tolerance");
  }

  // --- Argument validation ---------------------------------------------------
  {
    auto throws = [](double E, double nu, double h) {
      try {
        hex8_stiffness(E, nu, h);
      } catch (const std::invalid_argument&) {
        return true;
      }
      return false;
    };
    CHECK(throws(0.0, 0.3, 1.0), "E == 0 rejected");
    CHECK(throws(-1.0, 0.3, 1.0), "negative E rejected");
    CHECK(throws(1.0, 0.5, 1.0), "poisson == 0.5 rejected (incompressible)");
    CHECK(throws(1.0, 0.6, 1.0), "poisson > 0.5 rejected");
    CHECK(throws(1.0, 0.3, 0.0), "element_size == 0 rejected");
    CHECK(throws(1.0, 0.3, -2.0), "negative element_size rejected");
    // A valid call does not throw.
    bool ok = true;
    try {
      hex8_stiffness(1.0, 0.3, 1.0);
    } catch (...) {
      ok = false;
    }
    CHECK(ok, "valid arguments do not throw");
  }

  if (g_failures == 0) {
    std::printf("hex element: all %d checks passed\n", g_checks);
    return 0;
  }
  std::fprintf(stderr, "hex element: %d/%d checks FAILED\n", g_failures,
               g_checks);
  return 1;
}
