// M6.3 validation — Gate V2, PROJECTED formulation: the volume-fraction-
// targeted SIMP loop with single-field Heaviside projection and beta
// continuation (simp_optimize with a projection schedule) on the 3D cantilever
// and clamped-beam benchmarks reproduces the reference values committed in
// core/tests/fixtures/benchmarks.json (ARCHITECTURE §7 V2).
//
// The fixture is human-authored and IMMUTABLE (ARCHITECTURE §1/§8); it was
// regenerated by the maintainer's independent reference implementation for the
// projected formulation (DECISIONS.md 2026-07-10), superseding the unprojected
// 2026-07-05 benchmarks, and its "_comment" mandates: "The Gate V2 test must
// be updated to this formulation by the M6.3 agent" — this file is that
// update. The formulation is locked by the fixture's "formulation_locked"
// block:
//   x --density filter (rmin 2.5)--> rho_tilde --tanh projection (eta 0.5)-->
//   rho_bar --clamp[rho_min,1]--> E = rho_bar^p * E0,
//   beta in {1,2,4,8,16,32}, exactly 50 OC iterations per stage (300 total),
//   OC move 0.2 for beta <= 8, 0.1 at 16, 0.05 at 32, volume constraint on the
//   PROJECTED density, projection derivative chained BEFORE the filter
//   transpose, unclamped-dv OC ratio with 0/0 -> hold.
// The gates asserted are exactly the ones the fixture declares per benchmark:
//   * stage-end compliance at beta 1 and beta 8 (smooth regime, 1% relative),
//   * the final post-continuation analysis compliance (a BAND for the
//     cantilever, which settles into a period-2 limit cycle at beta 32; a
//     value +/- 5% for the clamped beam, which converges to a fixed point),
//   * achieved projected volume fraction within 0.01 absolute,
//   * exactly one 6-connected component of the thresholded (rho_bar > 0.5) set,
//   * y-symmetry error and discreteness M_nd bounds.
// The fixture's "informational_only" quantities (solid voxel counts,
// min-feature counts, the beta-32 stage sample) are printed, not gated.
// The fixture's "projection_unit_reference" block is additionally asserted
// exactly (rel tol 1e-12) against heaviside_project / _derivative.
//
// No third-party test framework (ARCHITECTURE §4); the same self-contained
// CHECK harness and test-local JSON reader as test_fea.cpp, public API only.

#include "topopt/fea.hpp"
#include "topopt/simp.hpp"
#include "topopt/voxel.hpp"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

using topopt::DirichletBC;
using topopt::NodalLoad;
using topopt::ProjectionStage;
using topopt::SimpOptimizeResult;
using topopt::SimpOptions;
using topopt::SimpParams;
using topopt::VoxelGrid;
using topopt::VoxelTag;

static int g_failures = 0;
static int g_checks = 0;

#define CHECK(cond, msg)                                            \
  do {                                                             \
    ++g_checks;                                                    \
    if (!(cond)) {                                                 \
      ++g_failures;                                                \
      std::fprintf(stderr, "FAIL (line %d): %s\n", __LINE__, msg); \
    }                                                              \
  } while (0)

namespace {

// --- Minimal, test-local JSON reader (same idiom as test_fea.cpp) ----------
struct Json {
  enum class T { Num, Str, Arr, Obj, Bool, Null } t = T::Num;
  double num = 0.0;
  bool boolean = false;
  std::string str;
  std::vector<Json> arr;
  std::vector<std::pair<std::string, Json>> obj;
  bool has(const std::string& key) const {
    for (const auto& kv : obj)
      if (kv.first == key) return true;
    return false;
  }
  const Json& at(const std::string& key) const {
    for (const auto& kv : obj)
      if (kv.first == key) return kv.second;
    throw std::runtime_error("missing JSON key: " + key);
  }
};

class JsonParser {
 public:
  explicit JsonParser(const std::string& s) : s_(s) {}
  Json parse() {
    skip_ws();
    Json v = value();
    skip_ws();
    if (pos_ != s_.size()) throw std::runtime_error("trailing JSON characters");
    return v;
  }

 private:
  const std::string& s_;
  std::size_t pos_ = 0;

  void skip_ws() {
    while (pos_ < s_.size()) {
      char c = s_[pos_];
      if (c == ' ' || c == '\t' || c == '\n' || c == '\r') ++pos_;
      else break;
    }
  }
  char peek() {
    if (pos_ >= s_.size()) throw std::runtime_error("unexpected end of JSON");
    return s_[pos_];
  }
  Json value() {
    skip_ws();
    char c = peek();
    if (c == '{') return object();
    if (c == '[') return array();
    if (c == '"') {
      Json v;
      v.t = Json::T::Str;
      v.str = string();
      return v;
    }
    if (c == '-' || (c >= '0' && c <= '9')) return number();
    if (c == 't' || c == 'f') return boolean();
    if (c == 'n') return null_literal();
    throw std::runtime_error(std::string("unexpected JSON character '") + c +
                             "'");
  }
  Json boolean() {
    Json v;
    v.t = Json::T::Bool;
    if (s_.compare(pos_, 4, "true") == 0) {
      v.boolean = true;
      pos_ += 4;
    } else if (s_.compare(pos_, 5, "false") == 0) {
      v.boolean = false;
      pos_ += 5;
    } else {
      throw std::runtime_error("invalid JSON boolean literal");
    }
    return v;
  }
  Json null_literal() {
    if (s_.compare(pos_, 4, "null") != 0)
      throw std::runtime_error("invalid JSON null literal");
    pos_ += 4;
    Json v;
    v.t = Json::T::Null;
    return v;
  }
  Json object() {
    Json v;
    v.t = Json::T::Obj;
    ++pos_;  // '{'
    skip_ws();
    if (peek() == '}') {
      ++pos_;
      return v;
    }
    while (true) {
      skip_ws();
      if (peek() != '"') throw std::runtime_error("expected JSON object key");
      std::string key = string();
      skip_ws();
      if (peek() != ':') throw std::runtime_error("expected ':' in object");
      ++pos_;
      v.obj.emplace_back(std::move(key), value());
      skip_ws();
      char n = peek();
      ++pos_;
      if (n == ',') continue;
      if (n == '}') break;
      throw std::runtime_error("expected ',' or '}' in object");
    }
    return v;
  }
  Json array() {
    Json v;
    v.t = Json::T::Arr;
    ++pos_;  // '['
    skip_ws();
    if (peek() == ']') {
      ++pos_;
      return v;
    }
    while (true) {
      v.arr.push_back(value());
      skip_ws();
      char n = peek();
      ++pos_;
      if (n == ',') continue;
      if (n == ']') break;
      throw std::runtime_error("expected ',' or ']' in array");
    }
    return v;
  }
  Json number() {
    std::size_t start = pos_;
    if (peek() == '-') ++pos_;
    while (pos_ < s_.size()) {
      char c = s_[pos_];
      if ((c >= '0' && c <= '9') || c == '.' || c == 'e' || c == 'E' ||
          c == '+' || c == '-')
        ++pos_;
      else
        break;
    }
    Json v;
    v.t = Json::T::Num;
    v.num = std::stod(s_.substr(start, pos_ - start));
    return v;
  }
  std::string string() {
    ++pos_;  // opening quote
    std::string out;
    while (true) {
      if (pos_ >= s_.size()) throw std::runtime_error("unterminated string");
      char c = s_[pos_++];
      if (c == '"') break;
      if (c == '\\') {
        if (pos_ >= s_.size()) throw std::runtime_error("unterminated escape");
        char e = s_[pos_++];
        switch (e) {
          case '"': out.push_back('"'); break;
          case '\\': out.push_back('\\'); break;
          case '/': out.push_back('/'); break;
          case 'n': out.push_back('\n'); break;
          case 't': out.push_back('\t'); break;
          default: out.push_back(e); break;
        }
      } else {
        out.push_back(c);
      }
    }
    return out;
  }
};

Json load_json(const std::string& path) {
  std::ifstream in(path, std::ios::binary);
  if (!in) throw std::runtime_error("cannot open fixture: " + path);
  std::ostringstream ss;
  ss << in.rdbuf();
  return JsonParser(ss.str()).parse();
}

// A fully-solid design grid (every voxel is a design voxel, matching the
// benchmarks' all-voxels-design setup, unchanged from the superseded fixture).
VoxelGrid solid_grid(int nx, int ny, int nz, double h) {
  VoxelGrid g;
  g.nx = nx;
  g.ny = ny;
  g.nz = nz;
  g.spacing = h;
  g.origin = topopt::Vec3{0.0, 0.0, 0.0};
  g.tags.assign(static_cast<std::size_t>(nx) * ny * nz, VoxelTag::Interior);
  return g;
}

// 6-connected components of the thresholded (rho > thr) voxel set.
struct Components {
  std::vector<int> label;  // grid-indexed; -1 where rho <= thr
  std::vector<int> size;   // voxel count per component id
  int dominant = -1;       // id of the largest component (-1 if none)
};

Components connected_components(const VoxelGrid& g,
                               const std::vector<double>& rho, double thr) {
  Components c;
  c.label.assign(g.voxel_count(), -1);
  auto solid = [&](int i, int j, int k) {
    return rho[g.index(i, j, k)] > thr;
  };
  std::vector<std::size_t> stack;
  for (int k = 0; k < g.nz; ++k)
    for (int j = 0; j < g.ny; ++j)
      for (int i = 0; i < g.nx; ++i) {
        if (!solid(i, j, k) || c.label[g.index(i, j, k)] != -1) continue;
        const int id = static_cast<int>(c.size.size());
        int count = 0;
        stack.clear();
        c.label[g.index(i, j, k)] = id;
        stack.push_back(g.index(i, j, k));
        while (!stack.empty()) {
          const std::size_t idx = stack.back();
          stack.pop_back();
          ++count;
          const int ci = static_cast<int>(idx % g.nx);
          const int cj = static_cast<int>((idx / g.nx) % g.ny);
          const int ck = static_cast<int>(idx / (static_cast<std::size_t>(g.nx) * g.ny));
          const int off[6][3] = {{1, 0, 0}, {-1, 0, 0}, {0, 1, 0},
                                 {0, -1, 0}, {0, 0, 1}, {0, 0, -1}};
          for (const auto& o : off) {
            const int ni = ci + o[0], nj = cj + o[1], nk = ck + o[2];
            if (ni < 0 || ni >= g.nx || nj < 0 || nj >= g.ny || nk < 0 ||
                nk >= g.nz)
              continue;
            if (!solid(ni, nj, nk) || c.label[g.index(ni, nj, nk)] != -1)
              continue;
            c.label[g.index(ni, nj, nk)] = id;
            stack.push_back(g.index(ni, nj, nk));
          }
        }
        c.size.push_back(count);
      }
  int best = -1;
  for (std::size_t s = 0; s < c.size.size(); ++s)
    if (best < 0 || c.size[s] > c.size[static_cast<std::size_t>(best)])
      best = static_cast<int>(s);
  c.dominant = best;
  return c;
}

// Discreteness measure M_nd = sum_e 4 rho_e (1 - rho_e) / n_design over the
// design (solid) voxels — 0 for a fully black/white field, 1 for uniform 0.5.
double discreteness_mnd(const VoxelGrid& g, const std::vector<double>& rho) {
  double acc = 0.0;
  std::size_t n = 0;
  for (int k = 0; k < g.nz; ++k)
    for (int j = 0; j < g.ny; ++j)
      for (int i = 0; i < g.nx; ++i) {
        if (!g.solid(i, j, k)) continue;
        const double r = rho[g.index(i, j, k)];
        acc += 4.0 * r * (1.0 - r);
        ++n;
      }
  return n > 0 ? acc / static_cast<double>(n) : 0.0;
}

// Max |rho(i,j,k) - rho(i,ny-1-j,k)| — both benchmark problems are symmetric
// about the mid-y plane, so the field must be too (fixture gate).
double y_symmetry_error(const VoxelGrid& g, const std::vector<double>& rho) {
  double err = 0.0;
  for (int k = 0; k < g.nz; ++k)
    for (int j = 0; j < g.ny; ++j)
      for (int i = 0; i < g.nx; ++i)
        err = std::max(err, std::fabs(rho[g.index(i, j, k)] -
                                      rho[g.index(i, g.ny - 1 - j, k)]));
  return err;
}

// Reference comparison at rel tol `rel`; exact-zero references compare at the
// same magnitude absolutely.
bool near_ref(double a, double ref, double rel) {
  if (ref == 0.0) return std::fabs(a) <= rel;
  return std::fabs(a - ref) <= rel * std::fabs(ref);
}

}  // namespace

int main() {
  const std::string path = std::string(BENCH_FIXTURE_DIR) + "/benchmarks.json";
  const Json root = load_json(path);

  // ==========================================================================
  // 1. projection_unit_reference: heaviside_project and its derivative match
  //    the maintainer's analytic spot values exactly (rel tol 1e-12, eta 0.5).
  // ==========================================================================
  {
    const Json& pur = root.at("projection_unit_reference");
    int spots = 0;
    for (const auto& bkv : pur.obj) {
      if (bkv.first.rfind("beta_", 0) != 0) continue;  // skip "_comment"
      const double beta = std::stod(bkv.first.substr(5));
      for (const auto& rkv : bkv.second.obj) {
        if (rkv.first.rfind("rt_", 0) != 0) continue;
        const double rt = std::stod(rkv.first.substr(3));
        const double v_ref = rkv.second.at("value").num;
        const double d_ref = rkv.second.at("derivative").num;
        const double v = topopt::heaviside_project(rt, beta, 0.5);
        const double d = topopt::heaviside_project_derivative(rt, beta, 0.5);
        CHECK(near_ref(v, v_ref, 1e-12),
              "projection: value matches the unit reference (rel 1e-12)");
        CHECK(near_ref(d, d_ref, 1e-12),
              "projection: derivative matches the unit reference (rel 1e-12)");
        ++spots;
      }
    }
    CHECK(spots == 15, "projection: all 15 unit-reference spots present");
  }

  // ==========================================================================
  // 2. The library's continuation schedule is the fixture-locked one:
  //    beta {1,2,4,8,16,32}, exactly 50 OC iterations per stage, move 0.2 for
  //    beta <= 8, 0.1 at beta = 16, 0.05 at beta = 32.
  // ==========================================================================
  const std::vector<ProjectionStage> sched =
      topopt::heaviside_continuation_schedule();
  {
    CHECK(sched.size() == 6, "schedule: 6 beta-continuation stages");
    const double betas[6] = {1.0, 2.0, 4.0, 8.0, 16.0, 32.0};
    const double moves[6] = {0.2, 0.2, 0.2, 0.2, 0.1, 0.05};
    for (std::size_t s = 0; s < sched.size() && s < 6; ++s) {
      CHECK(sched[s].beta == betas[s], "schedule: beta doubles 1 -> 32");
      CHECK(sched[s].move == moves[s], "schedule: locked move per stage");
      CHECK(sched[s].iterations == 50, "schedule: 50 OC iterations per stage");
    }
  }

  // ==========================================================================
  // 3. Gate V2 benchmarks under the locked projected formulation.
  // ==========================================================================
  const Json& benches = root.at("benchmarks");

  // Locked run parameters ("formulation_locked" / "solver_note"): filter
  // rmin = 2.5, eta = 0.5, no early stop (exactly 50 iterations per stage),
  // material law / OC damping / initial design identical to the superseded
  // formulation (p = 3, rho_min = 0.001, x0 = volfrac uniform), CG tol 1e-9.
  const double kFilterRadius = 2.5;
  const double kCgTol = 1e-9;

  for (const auto& kv : benches.obj) {
    const std::string& name = kv.first;
    const Json& b = kv.second;

    // Geometry/BCs/loads/material/volfrac are IDENTICAL to the superseded
    // fixture (fixture "problem" strings): 1.0-spaced solid grids, E0 = 1,
    // nu = 0.3, volfrac = 0.3, keyed by benchmark name below.
    int nx = 0, ny = 8, nz = 8;
    if (name == "cantilever_24x8x8") nx = 24;
    else if (name == "clamped_beam_48x8x8") nx = 48;
    const double h = 1.0, E0 = 1.0, nu = 0.3, volfrac = 0.3;

    const Json& ref = b.at("reference");
    const Json& gates = b.at("gates");

    VoxelGrid g = solid_grid(nx, ny, nz, h);

    std::vector<DirichletBC> bcs;
    std::vector<NodalLoad> loads;
    auto clamp_face = [&](int a) {  // clamp all 3 DOF of every node on x = a
      for (int c = 0; c <= nz; ++c)
        for (int bb = 0; bb <= ny; ++bb) {
          const int n = topopt::fea_node_index(g, a, bb, c);
          bcs.push_back({n, 0, 0.0});
          bcs.push_back({n, 1, 0.0});
          bcs.push_back({n, 2, 0.0});
        }
    };
    if (name == "cantilever_24x8x8") {
      // Clamp the x=0 face; total Fz = -1 spread over all (ny+1)(nz+1) = 81
      // tip-face nodes.
      clamp_face(0);
      const double fz = -1.0 / static_cast<double>((ny + 1) * (nz + 1));
      for (int c = 0; c <= nz; ++c)
        for (int bb = 0; bb <= ny; ++bb)
          loads.push_back({topopt::fea_node_index(g, nx, bb, c), 2, fz});
    } else if (name == "clamped_beam_48x8x8") {
      // Clamp BOTH the x=0 and x=nx faces; total Fz = -1 spread over the
      // (ny+1) = 9 nodes of the top center line (i = nx/2, k = nz, all j).
      clamp_face(0);
      clamp_face(nx);
      const double fz = -1.0 / static_cast<double>(ny + 1);
      for (int bb = 0; bb <= ny; ++bb)
        loads.push_back({topopt::fea_node_index(g, nx / 2, bb, nz), 2, fz});
    } else {
      std::fprintf(stderr, "FAIL: unknown benchmark '%s' in fixture\n",
                   name.c_str());
      ++g_failures;
      ++g_checks;
      continue;
    }

    SimpParams p;
    p.youngs_modulus = E0;
    p.poisson = nu;
    p.penalty = 3.0;
    p.density_min = 0.001;

    SimpOptions opt;
    opt.volume_fraction = volfrac;
    opt.filter_radius = kFilterRadius;
    opt.change_tol = 0.0;  // exactly 50 iterations per stage, like the reference
    opt.cg_tolerance = kCgTol;
    opt.cg_max_iterations = 0;
    opt.projection = sched;
    opt.projection_eta = 0.5;

    const SimpOptimizeResult r = topopt::simp_optimize(g, p, bcs, loads, opt);

    // Trajectory shape: 6 stages x 50 iterations, none stopped early.
    CHECK(r.iterations == 300, "V2: 300 OC iterations (6 stages x 50)");
    CHECK(r.history.size() == 300, "V2: one history entry per iteration");
    CHECK(!r.converged, "V2: change_tol 0 never flags converged");

    // The per-stage move limits were honoured by every OC step.
    bool moves_ok = r.history.size() == 300;
    for (std::size_t s = 0; moves_ok && s < sched.size(); ++s)
      for (int it = 0; it < sched[s].iterations; ++it)
        if (r.history[s * 50 + static_cast<std::size_t>(it)].change >
            sched[s].move + 1e-9)
          moves_ok = false;
    CHECK(moves_ok, "V2: every OC step respects its stage's move limit");

    // Stage-end compliances: history[50k-1].compliance is the last pre-update
    // analysis of stage k (the reference's stage-end sample; see the fixture's
    // limit_cycle_note distinguishing it from the final post-update analysis).
    double stage_end[6] = {0, 0, 0, 0, 0, 0};
    if (r.history.size() == 300)
      for (int s = 0; s < 6; ++s)
        stage_end[s] = r.history[static_cast<std::size_t>(50 * (s + 1) - 1)]
                           .compliance;

    const Components comps = connected_components(g, r.physical_density, 0.5);
    int total_solids = 0;
    for (int s : comps.size) total_solids += s;
    const double mnd = discreteness_mnd(g, r.physical_density);
    const double ysym = y_symmetry_error(g, r.physical_density);

    std::printf("[%s] %dx%dx%d volfrac %.2f, %d iters, final beta %.0f\n",
                name.c_str(), nx, ny, nz, volfrac, r.iterations,
                sched.back().beta);
    const Json& se_ref = ref.at("stage_end_compliance");
    for (int s = 0; s < 6; ++s) {
      char key[8];
      std::snprintf(key, sizeof(key), "%d", 1 << s);
      std::printf("  stage beta %2d end compliance %.6f (ref %.6f)\n", 1 << s,
                  stage_end[s], se_ref.at(key).num);
    }
    std::printf("  final analysis compliance %.6f (ref %.6f)\n", r.compliance,
                ref.at("final_analysis_compliance").num);
    std::printf("  projected volume fraction %.8f (ref %.8f)\n",
                r.volume_fraction,
                ref.at("achieved_projected_volume_fraction").num);
    std::printf("  thresholded(0.5): %d solid voxels (ref info %d), "
                "%d components, Mnd %.6f, y-sym err %.3e\n",
                total_solids,
                static_cast<int>(ref.at("solid_voxels_at_0p5").num),
                static_cast<int>(comps.size.size()), mnd, ysym);

    // ---- Gate V2 assertions (exactly the fixture's "gates") ----------------
    // 1. Smooth-regime stage-end compliances at beta 1 and beta 8.
    {
      const Json& g1 = gates.at("stage_end_compliance_beta_1");
      CHECK(near_ref(stage_end[0], g1.at("value").num,
                     g1.at("rel_tolerance").num),
            "V2: stage-end compliance at beta 1 within the fixture tolerance");
      const Json& g8 = gates.at("stage_end_compliance_beta_8");
      CHECK(near_ref(stage_end[3], g8.at("value").num,
                     g8.at("rel_tolerance").num),
            "V2: stage-end compliance at beta 8 within the fixture tolerance");
    }
    // 2. Final post-continuation analysis compliance: a band where the fixture
    //    declares one (period-2 limit cycle), else value + rel tolerance.
    if (gates.has("final_analysis_compliance_band")) {
      const Json& band = gates.at("final_analysis_compliance_band");
      CHECK(r.compliance >= band.arr[0].num && r.compliance <= band.arr[1].num,
            "V2: final analysis compliance inside the fixture band");
    } else {
      const Json& gf = gates.at("final_analysis_compliance");
      CHECK(near_ref(r.compliance, gf.at("value").num,
                     gf.at("rel_tolerance").num),
            "V2: final analysis compliance within the fixture tolerance");
    }
    // 3. Achieved PROJECTED volume fraction (the constraint is enforced on the
    //    projected density) within the fixture's absolute tolerance.
    CHECK(std::fabs(r.volume_fraction -
                    ref.at("achieved_projected_volume_fraction").num) <=
              gates.at("achieved_projected_volume_fraction_abs_tolerance").num,
          "V2: achieved projected volume fraction within tolerance");
    // 4. Exactly one 6-connected component of the thresholded set.
    CHECK(static_cast<int>(comps.size.size()) ==
              static_cast<int>(gates.at("connected_components_at_0p5").num),
          "V2: thresholded design is a single connected component");
    // 5. y-symmetry of the projected field.
    CHECK(ysym <= gates.at("y_symmetry_error_max").num,
          "V2: projected density is y-symmetric within the fixture bound");
    // 6. Discreteness: projection must deliver a near-black/white design.
    CHECK(mnd <= gates.at("discreteness_Mnd_max").num,
          "V2: discreteness M_nd within the fixture bound");
  }

  if (g_failures == 0) {
    std::printf("gate v2 validation (projected): all %d checks passed\n",
                g_checks);
    return 0;
  }
  std::fprintf(stderr, "gate v2 validation (projected): %d/%d checks FAILED\n",
               g_failures, g_checks);
  return 1;
}
