// ComputeLocation.swift — WHERE a run executes (handoff 097, LAN offload Tier 2).
//
// The iPad is always the default and always present. When a Mac on the LAN is
// running "TopOpt Worker", it advertises the Bonjour service `_topopt._tcp` with
// its core fingerprint in the TXT record; this model BROWSES for those (NWBrowser)
// and surfaces each by its Bonjour name — the user never types an IP. Selecting a
// worker resolves its host:port (NWConnection) and caches a RemoteRunnerConfig the
// run flow uses; selecting "iPad" (or nothing) leaves the run byte-identical to
// before. An advanced manual host:port is offered as a fallback only.
//
// The selection persists per device (UserDefaults). The skew check compares a
// worker's advertised fingerprint to the app's own CoreFingerprint (generated by
// build_core.sh) so the picker can WARN before a run — the RemoteRunner's /health
// guard is the hard stop, this is the friendly heads-up.

import Foundation
import Combine
import Network

/// One worker discovered on the LAN. Identity is its Bonjour service name (stable
/// for a given Mac), so it persists across the endpoint churn of Wi-Fi roaming.
public struct DiscoveredWorker: Identifiable, Equatable {
    public let id: String                 // Bonjour service name, e.g. "Mac mini"
    public var name: String { id }
    /// The core fingerprint from the TXT record (nil if the worker didn't advertise
    /// one). Compared to `CoreFingerprint.value` to flag version skew before a run.
    public let fingerprint: String?
    let endpoint: NWEndpoint              // resolved to host:port on selection
}

/// The chosen compute location, persisted per device.
public enum ComputeChoice: Equatable, Codable {
    case local
    case worker(name: String)
    case manual(host: String, port: Int)
}

@MainActor
public final class ComputeLocationModel: ObservableObject {
    /// Workers currently visible on the LAN, sorted by name.
    @Published public private(set) var workers: [DiscoveredWorker] = []
    /// The user's choice. Setting it persists + (re)resolves the remote config.
    @Published public private(set) var choice: ComputeChoice = .local
    /// The resolved config for a remote choice, or nil for local / not-yet-resolved.
    /// The run flow reads THIS: nil → on-device bridge runner (byte-identical).
    @Published public private(set) var activeRemote: RemoteRunnerConfig?
    /// True while a selected worker's endpoint is still resolving.
    @Published public private(set) var resolving = false

    private let defaults: UserDefaults
    private let defaultsKey = "topopt.computeLocation.v1"
    private var browser: NWBrowser?

    public init(defaults: UserDefaults = .standard) {
        self.defaults = defaults
        restore()
    }

    // MARK: - Discovery

    /// Start browsing `_topopt._tcp`. Idempotent; safe to call on every appear.
    public func startBrowsing() {
        guard browser == nil else { return }
        let params = NWParameters()
        params.includePeerToPeer = true
        let b = NWBrowser(for: .bonjourWithTXTRecord(type: "_topopt._tcp", domain: nil),
                          using: params)
        b.browseResultsChangedHandler = { [weak self] results, _ in
            Task { @MainActor in self?.ingest(results) }
        }
        b.stateUpdateHandler = { [weak self] state in
            if case .failed = state { Task { @MainActor in self?.stopBrowsing() } }
        }
        browser = b
        b.start(queue: .main)
    }

    public func stopBrowsing() {
        browser?.cancel()
        browser = nil
    }

    private func ingest(_ results: Set<NWBrowser.Result>) {
        var found: [DiscoveredWorker] = []
        for r in results {
            guard case let .service(name, _, _, _) = r.endpoint else { continue }
            var fingerprint: String?
            if case let .bonjour(txt) = r.metadata { fingerprint = txt["fingerprint"] }
            found.append(DiscoveredWorker(id: name, fingerprint: fingerprint,
                                          endpoint: r.endpoint))
        }
        found.sort { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
        workers = found
        // If the persisted worker (re)appeared and we haven't resolved it yet,
        // resolve now so tapping Run just works.
        if case let .worker(name) = choice, activeRemote == nil,
           workers.contains(where: { $0.id == name }) {
            select(.worker(name: name))
        }
    }

    /// True when a worker's core differs from this app's — a run would be refused.
    public func isSkewed(_ w: DiscoveredWorker) -> Bool {
        guard let fp = w.fingerprint else { return false }   // unknown → don't cry wolf
        return fp != CoreFingerprint.value
    }

    /// The plain-English skew message shown in the picker + a pointer to the fix.
    public func skewMessage(_ w: DiscoveredWorker) -> String {
        "\(w.name)'s core is a different build than this app. Open TopOpt Worker on "
        + "the Mac and choose “Update core…”, then try again."
    }

    // MARK: - Selection

    public func select(_ choice: ComputeChoice) {
        self.choice = choice
        persist()
        activeRemote = nil
        switch choice {
        case .local:
            resolving = false
        case .manual(let host, let port):
            activeRemote = RemoteRunnerConfig(host: host, port: port,
                                              expectedFingerprint: CoreFingerprint.value)
            resolving = false
        case .worker(let name):
            guard let w = workers.first(where: { $0.id == name }) else { return }
            resolving = true
            resolve(w.endpoint) { [weak self] resolved in
                Task { @MainActor in
                    guard let self, case .worker(name) = self.choice else { return }
                    self.resolving = false
                    guard let (host, port) = resolved else { return }
                    self.activeRemote = RemoteRunnerConfig(
                        host: host, port: port, expectedFingerprint: CoreFingerprint.value)
                }
            }
        }
    }

    /// A short label for the current choice, for the bottom-bar pill.
    public var label: String {
        switch choice {
        case .local: return "iPad"
        case .worker(let name): return name
        case .manual(let host, _): return host
        }
    }

    /// Resolve a Bonjour service endpoint to a concrete host:port for URLSession by
    /// opening a throwaway NWConnection and reading its resolved path. LAN-typical
    /// IPv4 works directly; an IPv6 link-local address keeps its %zone (URLSession
    /// on Apple platforms accepts it). Times out via the connection's own failure.
    nonisolated private func resolve(_ endpoint: NWEndpoint,
                                     completion: @escaping ((String, Int)?) -> Void) {
        let conn = NWConnection(to: endpoint, using: .tcp)
        var finished = false
        func finish(_ result: (String, Int)?) {
            if finished { return }; finished = true
            conn.cancel()
            completion(result)
        }
        conn.stateUpdateHandler = { state in
            switch state {
            case .ready:
                if case let .hostPort(host, port) = conn.currentPath?.remoteEndpoint {
                    finish((Self.hostString(host), Int(port.rawValue)))
                } else { finish(nil) }
            case .failed, .cancelled:
                finish(nil)
            default:
                break
            }
        }
        conn.start(queue: .global())
    }

    nonisolated private static func hostString(_ host: NWEndpoint.Host) -> String {
        switch host {
        case .ipv4(let a): return "\(a)".components(separatedBy: "%").first ?? "\(a)"
        case .ipv6(let a): return "\(a)"
        case .name(let n, _): return n
        @unknown default: return "\(host)"
        }
    }

    // MARK: - Persistence (per device)

    private func persist() {
        if let data = try? JSONEncoder().encode(choice) {
            defaults.set(data, forKey: defaultsKey)
        }
    }

    private func restore() {
        guard let data = defaults.data(forKey: defaultsKey),
              let saved = try? JSONDecoder().decode(ComputeChoice.self, from: data)
        else { return }
        choice = saved
        // A saved manual address resolves immediately; a saved worker resolves once
        // discovery re-finds it (see `ingest`). Local needs nothing.
        if case .manual = saved { select(saved) }
    }
}
